package com.awf.model.orm.dbo;

import java.util.Date;

public class IMConnections extends IMConnectionsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.IMConnections.User1
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private Integer user1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.IMConnections.User2
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private Integer user2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.IMConnections.Status
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.IMConnections.ExpiredOn
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private Date expiredon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.IMConnections.ConnectionSaved
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String connectionsaved;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.IMConnections.User1
     *
     * @return the value of dbo.IMConnections.User1
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public Integer getUser1() {
        return user1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.IMConnections.User1
     *
     * @param user1 the value for dbo.IMConnections.User1
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setUser1(Integer user1) {
        this.user1 = user1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.IMConnections.User2
     *
     * @return the value of dbo.IMConnections.User2
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public Integer getUser2() {
        return user2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.IMConnections.User2
     *
     * @param user2 the value for dbo.IMConnections.User2
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setUser2(Integer user2) {
        this.user2 = user2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.IMConnections.Status
     *
     * @return the value of dbo.IMConnections.Status
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.IMConnections.Status
     *
     * @param status the value for dbo.IMConnections.Status
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.IMConnections.ExpiredOn
     *
     * @return the value of dbo.IMConnections.ExpiredOn
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public Date getExpiredon() {
        return expiredon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.IMConnections.ExpiredOn
     *
     * @param expiredon the value for dbo.IMConnections.ExpiredOn
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setExpiredon(Date expiredon) {
        this.expiredon = expiredon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.IMConnections.ConnectionSaved
     *
     * @return the value of dbo.IMConnections.ConnectionSaved
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getConnectionsaved() {
        return connectionsaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.IMConnections.ConnectionSaved
     *
     * @param connectionsaved the value for dbo.IMConnections.ConnectionSaved
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setConnectionsaved(String connectionsaved) {
        this.connectionsaved = connectionsaved == null ? null : connectionsaved.trim();
    }
}