package com.awf.model.orm.dbo;

import java.util.Date;

public class IMConnectionsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.IMConnections.ConnectionID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String connectionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.IMConnections.EstablishedOn
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private Date establishedon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.IMConnections.ConnectionID
     *
     * @return the value of dbo.IMConnections.ConnectionID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getConnectionid() {
        return connectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.IMConnections.ConnectionID
     *
     * @param connectionid the value for dbo.IMConnections.ConnectionID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setConnectionid(String connectionid) {
        this.connectionid = connectionid == null ? null : connectionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.IMConnections.EstablishedOn
     *
     * @return the value of dbo.IMConnections.EstablishedOn
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public Date getEstablishedon() {
        return establishedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.IMConnections.EstablishedOn
     *
     * @param establishedon the value for dbo.IMConnections.EstablishedOn
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setEstablishedon(Date establishedon) {
        this.establishedon = establishedon;
    }
}