package com.awf.model.orm.dbo;

import java.util.Date;

public class InternalMessengerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.MessageID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.MessageDateTime
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private Date messagedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.MessageID
     *
     * @return the value of dbo.InternalMessenger.MessageID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.MessageID
     *
     * @param messageid the value for dbo.InternalMessenger.MessageID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setMessageid(String messageid) {
        this.messageid = messageid == null ? null : messageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.MessageDateTime
     *
     * @return the value of dbo.InternalMessenger.MessageDateTime
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public Date getMessagedatetime() {
        return messagedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.MessageDateTime
     *
     * @param messagedatetime the value for dbo.InternalMessenger.MessageDateTime
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setMessagedatetime(Date messagedatetime) {
        this.messagedatetime = messagedatetime;
    }
}