package com.awf.model.orm.dbo;

public class InternalMessenger extends InternalMessengerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.ConnectionID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String connectionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.UserCode
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private Integer usercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.RecipientUserCode
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private Integer recipientusercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.DeliveryStatus
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String deliverystatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.DeleteStat
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String deletestat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.ConnectionID
     *
     * @return the value of dbo.InternalMessenger.ConnectionID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getConnectionid() {
        return connectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.ConnectionID
     *
     * @param connectionid the value for dbo.InternalMessenger.ConnectionID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setConnectionid(String connectionid) {
        this.connectionid = connectionid == null ? null : connectionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.UserCode
     *
     * @return the value of dbo.InternalMessenger.UserCode
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public Integer getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.UserCode
     *
     * @param usercode the value for dbo.InternalMessenger.UserCode
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setUsercode(Integer usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.RecipientUserCode
     *
     * @return the value of dbo.InternalMessenger.RecipientUserCode
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public Integer getRecipientusercode() {
        return recipientusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.RecipientUserCode
     *
     * @param recipientusercode the value for dbo.InternalMessenger.RecipientUserCode
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setRecipientusercode(Integer recipientusercode) {
        this.recipientusercode = recipientusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.DeliveryStatus
     *
     * @return the value of dbo.InternalMessenger.DeliveryStatus
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getDeliverystatus() {
        return deliverystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.DeliveryStatus
     *
     * @param deliverystatus the value for dbo.InternalMessenger.DeliveryStatus
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setDeliverystatus(String deliverystatus) {
        this.deliverystatus = deliverystatus == null ? null : deliverystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.DeleteStat
     *
     * @return the value of dbo.InternalMessenger.DeleteStat
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getDeletestat() {
        return deletestat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.DeleteStat
     *
     * @param deletestat the value for dbo.InternalMessenger.DeleteStat
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setDeletestat(String deletestat) {
        this.deletestat = deletestat == null ? null : deletestat.trim();
    }
}