package com.awf.model.orm.dbo;

public class InternalMessengerWithBLOBs extends InternalMessenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.MessageBody
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String messagebody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.AttachmentName
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String attachmentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.AttachmentType
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String attachmenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.AttachmentPath
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String attachmentpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.InternalMessenger.DeviceID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    private String deviceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.MessageBody
     *
     * @return the value of dbo.InternalMessenger.MessageBody
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getMessagebody() {
        return messagebody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.MessageBody
     *
     * @param messagebody the value for dbo.InternalMessenger.MessageBody
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setMessagebody(String messagebody) {
        this.messagebody = messagebody == null ? null : messagebody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.AttachmentName
     *
     * @return the value of dbo.InternalMessenger.AttachmentName
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getAttachmentname() {
        return attachmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.AttachmentName
     *
     * @param attachmentname the value for dbo.InternalMessenger.AttachmentName
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setAttachmentname(String attachmentname) {
        this.attachmentname = attachmentname == null ? null : attachmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.AttachmentType
     *
     * @return the value of dbo.InternalMessenger.AttachmentType
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getAttachmenttype() {
        return attachmenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.AttachmentType
     *
     * @param attachmenttype the value for dbo.InternalMessenger.AttachmentType
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setAttachmenttype(String attachmenttype) {
        this.attachmenttype = attachmenttype == null ? null : attachmenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.AttachmentPath
     *
     * @return the value of dbo.InternalMessenger.AttachmentPath
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getAttachmentpath() {
        return attachmentpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.AttachmentPath
     *
     * @param attachmentpath the value for dbo.InternalMessenger.AttachmentPath
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setAttachmentpath(String attachmentpath) {
        this.attachmentpath = attachmentpath == null ? null : attachmentpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.InternalMessenger.DeviceID
     *
     * @return the value of dbo.InternalMessenger.DeviceID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.InternalMessenger.DeviceID
     *
     * @param deviceid the value for dbo.InternalMessenger.DeviceID
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }
}