package com.awf.model.orm.dbo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InternalMessengerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public InternalMessengerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMessageidIsNull() {
            addCriterion("MessageID is null");
            return (Criteria) this;
        }

        public Criteria andMessageidIsNotNull() {
            addCriterion("MessageID is not null");
            return (Criteria) this;
        }

        public Criteria andMessageidEqualTo(String value) {
            addCriterion("MessageID =", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotEqualTo(String value) {
            addCriterion("MessageID <>", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidGreaterThan(String value) {
            addCriterion("MessageID >", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidGreaterThanOrEqualTo(String value) {
            addCriterion("MessageID >=", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidLessThan(String value) {
            addCriterion("MessageID <", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidLessThanOrEqualTo(String value) {
            addCriterion("MessageID <=", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidLike(String value) {
            addCriterion("MessageID like", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotLike(String value) {
            addCriterion("MessageID not like", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidIn(List<String> values) {
            addCriterion("MessageID in", values, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotIn(List<String> values) {
            addCriterion("MessageID not in", values, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidBetween(String value1, String value2) {
            addCriterion("MessageID between", value1, value2, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotBetween(String value1, String value2) {
            addCriterion("MessageID not between", value1, value2, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeIsNull() {
            addCriterion("MessageDateTime is null");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeIsNotNull() {
            addCriterion("MessageDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeEqualTo(Date value) {
            addCriterion("MessageDateTime =", value, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeNotEqualTo(Date value) {
            addCriterion("MessageDateTime <>", value, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeGreaterThan(Date value) {
            addCriterion("MessageDateTime >", value, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MessageDateTime >=", value, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeLessThan(Date value) {
            addCriterion("MessageDateTime <", value, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeLessThanOrEqualTo(Date value) {
            addCriterion("MessageDateTime <=", value, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeIn(List<Date> values) {
            addCriterion("MessageDateTime in", values, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeNotIn(List<Date> values) {
            addCriterion("MessageDateTime not in", values, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeBetween(Date value1, Date value2) {
            addCriterion("MessageDateTime between", value1, value2, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andMessagedatetimeNotBetween(Date value1, Date value2) {
            addCriterion("MessageDateTime not between", value1, value2, "messagedatetime");
            return (Criteria) this;
        }

        public Criteria andConnectionidIsNull() {
            addCriterion("ConnectionID is null");
            return (Criteria) this;
        }

        public Criteria andConnectionidIsNotNull() {
            addCriterion("ConnectionID is not null");
            return (Criteria) this;
        }

        public Criteria andConnectionidEqualTo(String value) {
            addCriterion("ConnectionID =", value, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidNotEqualTo(String value) {
            addCriterion("ConnectionID <>", value, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidGreaterThan(String value) {
            addCriterion("ConnectionID >", value, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidGreaterThanOrEqualTo(String value) {
            addCriterion("ConnectionID >=", value, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidLessThan(String value) {
            addCriterion("ConnectionID <", value, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidLessThanOrEqualTo(String value) {
            addCriterion("ConnectionID <=", value, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidLike(String value) {
            addCriterion("ConnectionID like", value, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidNotLike(String value) {
            addCriterion("ConnectionID not like", value, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidIn(List<String> values) {
            addCriterion("ConnectionID in", values, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidNotIn(List<String> values) {
            addCriterion("ConnectionID not in", values, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidBetween(String value1, String value2) {
            addCriterion("ConnectionID between", value1, value2, "connectionid");
            return (Criteria) this;
        }

        public Criteria andConnectionidNotBetween(String value1, String value2) {
            addCriterion("ConnectionID not between", value1, value2, "connectionid");
            return (Criteria) this;
        }

        public Criteria andUsercodeIsNull() {
            addCriterion("UserCode is null");
            return (Criteria) this;
        }

        public Criteria andUsercodeIsNotNull() {
            addCriterion("UserCode is not null");
            return (Criteria) this;
        }

        public Criteria andUsercodeEqualTo(Integer value) {
            addCriterion("UserCode =", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotEqualTo(Integer value) {
            addCriterion("UserCode <>", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeGreaterThan(Integer value) {
            addCriterion("UserCode >", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("UserCode >=", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLessThan(Integer value) {
            addCriterion("UserCode <", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLessThanOrEqualTo(Integer value) {
            addCriterion("UserCode <=", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeIn(List<Integer> values) {
            addCriterion("UserCode in", values, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotIn(List<Integer> values) {
            addCriterion("UserCode not in", values, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeBetween(Integer value1, Integer value2) {
            addCriterion("UserCode between", value1, value2, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotBetween(Integer value1, Integer value2) {
            addCriterion("UserCode not between", value1, value2, "usercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeIsNull() {
            addCriterion("RecipientUserCode is null");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeIsNotNull() {
            addCriterion("RecipientUserCode is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeEqualTo(Integer value) {
            addCriterion("RecipientUserCode =", value, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeNotEqualTo(Integer value) {
            addCriterion("RecipientUserCode <>", value, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeGreaterThan(Integer value) {
            addCriterion("RecipientUserCode >", value, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("RecipientUserCode >=", value, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeLessThan(Integer value) {
            addCriterion("RecipientUserCode <", value, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeLessThanOrEqualTo(Integer value) {
            addCriterion("RecipientUserCode <=", value, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeIn(List<Integer> values) {
            addCriterion("RecipientUserCode in", values, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeNotIn(List<Integer> values) {
            addCriterion("RecipientUserCode not in", values, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeBetween(Integer value1, Integer value2) {
            addCriterion("RecipientUserCode between", value1, value2, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andRecipientusercodeNotBetween(Integer value1, Integer value2) {
            addCriterion("RecipientUserCode not between", value1, value2, "recipientusercode");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusIsNull() {
            addCriterion("DeliveryStatus is null");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusIsNotNull() {
            addCriterion("DeliveryStatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusEqualTo(String value) {
            addCriterion("DeliveryStatus =", value, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusNotEqualTo(String value) {
            addCriterion("DeliveryStatus <>", value, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusGreaterThan(String value) {
            addCriterion("DeliveryStatus >", value, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusGreaterThanOrEqualTo(String value) {
            addCriterion("DeliveryStatus >=", value, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusLessThan(String value) {
            addCriterion("DeliveryStatus <", value, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusLessThanOrEqualTo(String value) {
            addCriterion("DeliveryStatus <=", value, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusLike(String value) {
            addCriterion("DeliveryStatus like", value, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusNotLike(String value) {
            addCriterion("DeliveryStatus not like", value, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusIn(List<String> values) {
            addCriterion("DeliveryStatus in", values, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusNotIn(List<String> values) {
            addCriterion("DeliveryStatus not in", values, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusBetween(String value1, String value2) {
            addCriterion("DeliveryStatus between", value1, value2, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeliverystatusNotBetween(String value1, String value2) {
            addCriterion("DeliveryStatus not between", value1, value2, "deliverystatus");
            return (Criteria) this;
        }

        public Criteria andDeletestatIsNull() {
            addCriterion("DeleteStat is null");
            return (Criteria) this;
        }

        public Criteria andDeletestatIsNotNull() {
            addCriterion("DeleteStat is not null");
            return (Criteria) this;
        }

        public Criteria andDeletestatEqualTo(String value) {
            addCriterion("DeleteStat =", value, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatNotEqualTo(String value) {
            addCriterion("DeleteStat <>", value, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatGreaterThan(String value) {
            addCriterion("DeleteStat >", value, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatGreaterThanOrEqualTo(String value) {
            addCriterion("DeleteStat >=", value, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatLessThan(String value) {
            addCriterion("DeleteStat <", value, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatLessThanOrEqualTo(String value) {
            addCriterion("DeleteStat <=", value, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatLike(String value) {
            addCriterion("DeleteStat like", value, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatNotLike(String value) {
            addCriterion("DeleteStat not like", value, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatIn(List<String> values) {
            addCriterion("DeleteStat in", values, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatNotIn(List<String> values) {
            addCriterion("DeleteStat not in", values, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatBetween(String value1, String value2) {
            addCriterion("DeleteStat between", value1, value2, "deletestat");
            return (Criteria) this;
        }

        public Criteria andDeletestatNotBetween(String value1, String value2) {
            addCriterion("DeleteStat not between", value1, value2, "deletestat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 12 10:36:58 GST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.InternalMessenger
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}