package com.awf.model.orm.dbo;

import java.util.Date;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.UserCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private Integer usercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.UserID
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.UserName
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.Password
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.CBCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String cbcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.CateCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private Integer catecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.CanDelete
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String candelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.CanDeleteItem
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String candeleteitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.CanApprove
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String canapprove;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.EmployeeCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String employeecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.Popups
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String popups;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.HideSalary
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String hidesalary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.CheckCreditControl
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String checkcreditcontrol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.BypassCreditControl
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String bypasscreditcontrol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.HideCostPrice
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String hidecostprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.UseESignature
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String useesignature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.ChangePaymentTerms
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String changepaymentterms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.ChangePrice
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String changeprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.HeadEmpCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String headempcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.Active
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String active;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.LicenceAlerts
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String licencealerts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.UnderCostSalesYN
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String undercostsalesyn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.SetPriceMatrixYN
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String setpricematrixyn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.CostSalesYN
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String costsalesyn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.Theme
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String theme;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.WorkingDoc
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String workingdoc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.ResetLogin
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String resetlogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.SysName
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String sysname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.LastLoginDate
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private Date lastlogindate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.Lastloginsys
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private String lastloginsys;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TBADAPA0016.UserSignature
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	private byte[] usersignature;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.UserCode
	 * @return  the value of dbo.TBADAPA0016.UserCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public Integer getUsercode() {
		return usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.UserCode
	 * @param usercode  the value for dbo.TBADAPA0016.UserCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setUsercode(Integer usercode) {
		this.usercode = usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.UserID
	 * @return  the value of dbo.TBADAPA0016.UserID
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.UserID
	 * @param userid  the value for dbo.TBADAPA0016.UserID
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.UserName
	 * @return  the value of dbo.TBADAPA0016.UserName
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.UserName
	 * @param username  the value for dbo.TBADAPA0016.UserName
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.Password
	 * @return  the value of dbo.TBADAPA0016.Password
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.Password
	 * @param password  the value for dbo.TBADAPA0016.Password
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.CBCode
	 * @return  the value of dbo.TBADAPA0016.CBCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getCbcode() {
		return cbcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.CBCode
	 * @param cbcode  the value for dbo.TBADAPA0016.CBCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setCbcode(String cbcode) {
		this.cbcode = cbcode == null ? null : cbcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.CateCode
	 * @return  the value of dbo.TBADAPA0016.CateCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public Integer getCatecode() {
		return catecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.CateCode
	 * @param catecode  the value for dbo.TBADAPA0016.CateCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setCatecode(Integer catecode) {
		this.catecode = catecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.CanDelete
	 * @return  the value of dbo.TBADAPA0016.CanDelete
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getCandelete() {
		return candelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.CanDelete
	 * @param candelete  the value for dbo.TBADAPA0016.CanDelete
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setCandelete(String candelete) {
		this.candelete = candelete == null ? null : candelete.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.CanDeleteItem
	 * @return  the value of dbo.TBADAPA0016.CanDeleteItem
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getCandeleteitem() {
		return candeleteitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.CanDeleteItem
	 * @param candeleteitem  the value for dbo.TBADAPA0016.CanDeleteItem
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setCandeleteitem(String candeleteitem) {
		this.candeleteitem = candeleteitem == null ? null : candeleteitem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.CanApprove
	 * @return  the value of dbo.TBADAPA0016.CanApprove
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getCanapprove() {
		return canapprove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.CanApprove
	 * @param canapprove  the value for dbo.TBADAPA0016.CanApprove
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setCanapprove(String canapprove) {
		this.canapprove = canapprove == null ? null : canapprove.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.EmployeeCode
	 * @return  the value of dbo.TBADAPA0016.EmployeeCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getEmployeecode() {
		return employeecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.EmployeeCode
	 * @param employeecode  the value for dbo.TBADAPA0016.EmployeeCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode == null ? null : employeecode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.Popups
	 * @return  the value of dbo.TBADAPA0016.Popups
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getPopups() {
		return popups;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.Popups
	 * @param popups  the value for dbo.TBADAPA0016.Popups
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setPopups(String popups) {
		this.popups = popups == null ? null : popups.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.HideSalary
	 * @return  the value of dbo.TBADAPA0016.HideSalary
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getHidesalary() {
		return hidesalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.HideSalary
	 * @param hidesalary  the value for dbo.TBADAPA0016.HideSalary
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setHidesalary(String hidesalary) {
		this.hidesalary = hidesalary == null ? null : hidesalary.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.CheckCreditControl
	 * @return  the value of dbo.TBADAPA0016.CheckCreditControl
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getCheckcreditcontrol() {
		return checkcreditcontrol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.CheckCreditControl
	 * @param checkcreditcontrol  the value for dbo.TBADAPA0016.CheckCreditControl
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setCheckcreditcontrol(String checkcreditcontrol) {
		this.checkcreditcontrol = checkcreditcontrol == null ? null : checkcreditcontrol.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.BypassCreditControl
	 * @return  the value of dbo.TBADAPA0016.BypassCreditControl
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getBypasscreditcontrol() {
		return bypasscreditcontrol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.BypassCreditControl
	 * @param bypasscreditcontrol  the value for dbo.TBADAPA0016.BypassCreditControl
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setBypasscreditcontrol(String bypasscreditcontrol) {
		this.bypasscreditcontrol = bypasscreditcontrol == null ? null : bypasscreditcontrol.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.HideCostPrice
	 * @return  the value of dbo.TBADAPA0016.HideCostPrice
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getHidecostprice() {
		return hidecostprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.HideCostPrice
	 * @param hidecostprice  the value for dbo.TBADAPA0016.HideCostPrice
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setHidecostprice(String hidecostprice) {
		this.hidecostprice = hidecostprice == null ? null : hidecostprice.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.UseESignature
	 * @return  the value of dbo.TBADAPA0016.UseESignature
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getUseesignature() {
		return useesignature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.UseESignature
	 * @param useesignature  the value for dbo.TBADAPA0016.UseESignature
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setUseesignature(String useesignature) {
		this.useesignature = useesignature == null ? null : useesignature.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.ChangePaymentTerms
	 * @return  the value of dbo.TBADAPA0016.ChangePaymentTerms
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getChangepaymentterms() {
		return changepaymentterms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.ChangePaymentTerms
	 * @param changepaymentterms  the value for dbo.TBADAPA0016.ChangePaymentTerms
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setChangepaymentterms(String changepaymentterms) {
		this.changepaymentterms = changepaymentterms == null ? null : changepaymentterms.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.ChangePrice
	 * @return  the value of dbo.TBADAPA0016.ChangePrice
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getChangeprice() {
		return changeprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.ChangePrice
	 * @param changeprice  the value for dbo.TBADAPA0016.ChangePrice
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setChangeprice(String changeprice) {
		this.changeprice = changeprice == null ? null : changeprice.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.HeadEmpCode
	 * @return  the value of dbo.TBADAPA0016.HeadEmpCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getHeadempcode() {
		return headempcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.HeadEmpCode
	 * @param headempcode  the value for dbo.TBADAPA0016.HeadEmpCode
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setHeadempcode(String headempcode) {
		this.headempcode = headempcode == null ? null : headempcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.Active
	 * @return  the value of dbo.TBADAPA0016.Active
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.Active
	 * @param active  the value for dbo.TBADAPA0016.Active
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setActive(String active) {
		this.active = active == null ? null : active.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.LicenceAlerts
	 * @return  the value of dbo.TBADAPA0016.LicenceAlerts
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getLicencealerts() {
		return licencealerts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.LicenceAlerts
	 * @param licencealerts  the value for dbo.TBADAPA0016.LicenceAlerts
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setLicencealerts(String licencealerts) {
		this.licencealerts = licencealerts == null ? null : licencealerts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.UnderCostSalesYN
	 * @return  the value of dbo.TBADAPA0016.UnderCostSalesYN
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getUndercostsalesyn() {
		return undercostsalesyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.UnderCostSalesYN
	 * @param undercostsalesyn  the value for dbo.TBADAPA0016.UnderCostSalesYN
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setUndercostsalesyn(String undercostsalesyn) {
		this.undercostsalesyn = undercostsalesyn == null ? null : undercostsalesyn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.SetPriceMatrixYN
	 * @return  the value of dbo.TBADAPA0016.SetPriceMatrixYN
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getSetpricematrixyn() {
		return setpricematrixyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.SetPriceMatrixYN
	 * @param setpricematrixyn  the value for dbo.TBADAPA0016.SetPriceMatrixYN
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setSetpricematrixyn(String setpricematrixyn) {
		this.setpricematrixyn = setpricematrixyn == null ? null : setpricematrixyn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.CostSalesYN
	 * @return  the value of dbo.TBADAPA0016.CostSalesYN
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getCostsalesyn() {
		return costsalesyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.CostSalesYN
	 * @param costsalesyn  the value for dbo.TBADAPA0016.CostSalesYN
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setCostsalesyn(String costsalesyn) {
		this.costsalesyn = costsalesyn == null ? null : costsalesyn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.Theme
	 * @return  the value of dbo.TBADAPA0016.Theme
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getTheme() {
		return theme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.Theme
	 * @param theme  the value for dbo.TBADAPA0016.Theme
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setTheme(String theme) {
		this.theme = theme == null ? null : theme.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.WorkingDoc
	 * @return  the value of dbo.TBADAPA0016.WorkingDoc
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getWorkingdoc() {
		return workingdoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.WorkingDoc
	 * @param workingdoc  the value for dbo.TBADAPA0016.WorkingDoc
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setWorkingdoc(String workingdoc) {
		this.workingdoc = workingdoc == null ? null : workingdoc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.ResetLogin
	 * @return  the value of dbo.TBADAPA0016.ResetLogin
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getResetlogin() {
		return resetlogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.ResetLogin
	 * @param resetlogin  the value for dbo.TBADAPA0016.ResetLogin
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setResetlogin(String resetlogin) {
		this.resetlogin = resetlogin == null ? null : resetlogin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.SysName
	 * @return  the value of dbo.TBADAPA0016.SysName
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getSysname() {
		return sysname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.SysName
	 * @param sysname  the value for dbo.TBADAPA0016.SysName
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setSysname(String sysname) {
		this.sysname = sysname == null ? null : sysname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.LastLoginDate
	 * @return  the value of dbo.TBADAPA0016.LastLoginDate
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public Date getLastlogindate() {
		return lastlogindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.LastLoginDate
	 * @param lastlogindate  the value for dbo.TBADAPA0016.LastLoginDate
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setLastlogindate(Date lastlogindate) {
		this.lastlogindate = lastlogindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.Lastloginsys
	 * @return  the value of dbo.TBADAPA0016.Lastloginsys
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getLastloginsys() {
		return lastloginsys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.Lastloginsys
	 * @param lastloginsys  the value for dbo.TBADAPA0016.Lastloginsys
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setLastloginsys(String lastloginsys) {
		this.lastloginsys = lastloginsys == null ? null : lastloginsys.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TBADAPA0016.UserSignature
	 * @return  the value of dbo.TBADAPA0016.UserSignature
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public byte[] getUsersignature() {
		return usersignature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TBADAPA0016.UserSignature
	 * @param usersignature  the value for dbo.TBADAPA0016.UserSignature
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setUsersignature(byte[] usersignature) {
		this.usersignature = usersignature;
	}
}