package com.awf.model.orm.dbo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public UsersExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUsercodeIsNull() {
			addCriterion("UserCode is null");
			return (Criteria) this;
		}

		public Criteria andUsercodeIsNotNull() {
			addCriterion("UserCode is not null");
			return (Criteria) this;
		}

		public Criteria andUsercodeEqualTo(Integer value) {
			addCriterion("UserCode =", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeNotEqualTo(Integer value) {
			addCriterion("UserCode <>", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeGreaterThan(Integer value) {
			addCriterion("UserCode >", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("UserCode >=", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeLessThan(Integer value) {
			addCriterion("UserCode <", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeLessThanOrEqualTo(Integer value) {
			addCriterion("UserCode <=", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeIn(List<Integer> values) {
			addCriterion("UserCode in", values, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeNotIn(List<Integer> values) {
			addCriterion("UserCode not in", values, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeBetween(Integer value1, Integer value2) {
			addCriterion("UserCode between", value1, value2, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeNotBetween(Integer value1, Integer value2) {
			addCriterion("UserCode not between", value1, value2, "usercode");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("UserID is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("UserID is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("UserID =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("UserID <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("UserID >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("UserID >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("UserID <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("UserID <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("UserID like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("UserID not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("UserID in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("UserID not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("UserID between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("UserID not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("UserName is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("UserName is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("UserName =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("UserName <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("UserName >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("UserName >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("UserName <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("UserName <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("UserName like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("UserName not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("UserName in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("UserName not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("UserName between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("UserName not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("Password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("Password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("Password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("Password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("Password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("Password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("Password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("Password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("Password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("Password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("Password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("Password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("Password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("Password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andCbcodeIsNull() {
			addCriterion("CBCode is null");
			return (Criteria) this;
		}

		public Criteria andCbcodeIsNotNull() {
			addCriterion("CBCode is not null");
			return (Criteria) this;
		}

		public Criteria andCbcodeEqualTo(String value) {
			addCriterion("CBCode =", value, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeNotEqualTo(String value) {
			addCriterion("CBCode <>", value, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeGreaterThan(String value) {
			addCriterion("CBCode >", value, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeGreaterThanOrEqualTo(String value) {
			addCriterion("CBCode >=", value, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeLessThan(String value) {
			addCriterion("CBCode <", value, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeLessThanOrEqualTo(String value) {
			addCriterion("CBCode <=", value, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeLike(String value) {
			addCriterion("CBCode like", value, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeNotLike(String value) {
			addCriterion("CBCode not like", value, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeIn(List<String> values) {
			addCriterion("CBCode in", values, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeNotIn(List<String> values) {
			addCriterion("CBCode not in", values, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeBetween(String value1, String value2) {
			addCriterion("CBCode between", value1, value2, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCbcodeNotBetween(String value1, String value2) {
			addCriterion("CBCode not between", value1, value2, "cbcode");
			return (Criteria) this;
		}

		public Criteria andCatecodeIsNull() {
			addCriterion("CateCode is null");
			return (Criteria) this;
		}

		public Criteria andCatecodeIsNotNull() {
			addCriterion("CateCode is not null");
			return (Criteria) this;
		}

		public Criteria andCatecodeEqualTo(Integer value) {
			addCriterion("CateCode =", value, "catecode");
			return (Criteria) this;
		}

		public Criteria andCatecodeNotEqualTo(Integer value) {
			addCriterion("CateCode <>", value, "catecode");
			return (Criteria) this;
		}

		public Criteria andCatecodeGreaterThan(Integer value) {
			addCriterion("CateCode >", value, "catecode");
			return (Criteria) this;
		}

		public Criteria andCatecodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("CateCode >=", value, "catecode");
			return (Criteria) this;
		}

		public Criteria andCatecodeLessThan(Integer value) {
			addCriterion("CateCode <", value, "catecode");
			return (Criteria) this;
		}

		public Criteria andCatecodeLessThanOrEqualTo(Integer value) {
			addCriterion("CateCode <=", value, "catecode");
			return (Criteria) this;
		}

		public Criteria andCatecodeIn(List<Integer> values) {
			addCriterion("CateCode in", values, "catecode");
			return (Criteria) this;
		}

		public Criteria andCatecodeNotIn(List<Integer> values) {
			addCriterion("CateCode not in", values, "catecode");
			return (Criteria) this;
		}

		public Criteria andCatecodeBetween(Integer value1, Integer value2) {
			addCriterion("CateCode between", value1, value2, "catecode");
			return (Criteria) this;
		}

		public Criteria andCatecodeNotBetween(Integer value1, Integer value2) {
			addCriterion("CateCode not between", value1, value2, "catecode");
			return (Criteria) this;
		}

		public Criteria andCandeleteIsNull() {
			addCriterion("CanDelete is null");
			return (Criteria) this;
		}

		public Criteria andCandeleteIsNotNull() {
			addCriterion("CanDelete is not null");
			return (Criteria) this;
		}

		public Criteria andCandeleteEqualTo(String value) {
			addCriterion("CanDelete =", value, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteNotEqualTo(String value) {
			addCriterion("CanDelete <>", value, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteGreaterThan(String value) {
			addCriterion("CanDelete >", value, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteGreaterThanOrEqualTo(String value) {
			addCriterion("CanDelete >=", value, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteLessThan(String value) {
			addCriterion("CanDelete <", value, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteLessThanOrEqualTo(String value) {
			addCriterion("CanDelete <=", value, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteLike(String value) {
			addCriterion("CanDelete like", value, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteNotLike(String value) {
			addCriterion("CanDelete not like", value, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteIn(List<String> values) {
			addCriterion("CanDelete in", values, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteNotIn(List<String> values) {
			addCriterion("CanDelete not in", values, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteBetween(String value1, String value2) {
			addCriterion("CanDelete between", value1, value2, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteNotBetween(String value1, String value2) {
			addCriterion("CanDelete not between", value1, value2, "candelete");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemIsNull() {
			addCriterion("CanDeleteItem is null");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemIsNotNull() {
			addCriterion("CanDeleteItem is not null");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemEqualTo(String value) {
			addCriterion("CanDeleteItem =", value, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemNotEqualTo(String value) {
			addCriterion("CanDeleteItem <>", value, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemGreaterThan(String value) {
			addCriterion("CanDeleteItem >", value, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemGreaterThanOrEqualTo(String value) {
			addCriterion("CanDeleteItem >=", value, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemLessThan(String value) {
			addCriterion("CanDeleteItem <", value, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemLessThanOrEqualTo(String value) {
			addCriterion("CanDeleteItem <=", value, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemLike(String value) {
			addCriterion("CanDeleteItem like", value, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemNotLike(String value) {
			addCriterion("CanDeleteItem not like", value, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemIn(List<String> values) {
			addCriterion("CanDeleteItem in", values, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemNotIn(List<String> values) {
			addCriterion("CanDeleteItem not in", values, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemBetween(String value1, String value2) {
			addCriterion("CanDeleteItem between", value1, value2, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCandeleteitemNotBetween(String value1, String value2) {
			addCriterion("CanDeleteItem not between", value1, value2, "candeleteitem");
			return (Criteria) this;
		}

		public Criteria andCanapproveIsNull() {
			addCriterion("CanApprove is null");
			return (Criteria) this;
		}

		public Criteria andCanapproveIsNotNull() {
			addCriterion("CanApprove is not null");
			return (Criteria) this;
		}

		public Criteria andCanapproveEqualTo(String value) {
			addCriterion("CanApprove =", value, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveNotEqualTo(String value) {
			addCriterion("CanApprove <>", value, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveGreaterThan(String value) {
			addCriterion("CanApprove >", value, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveGreaterThanOrEqualTo(String value) {
			addCriterion("CanApprove >=", value, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveLessThan(String value) {
			addCriterion("CanApprove <", value, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveLessThanOrEqualTo(String value) {
			addCriterion("CanApprove <=", value, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveLike(String value) {
			addCriterion("CanApprove like", value, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveNotLike(String value) {
			addCriterion("CanApprove not like", value, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveIn(List<String> values) {
			addCriterion("CanApprove in", values, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveNotIn(List<String> values) {
			addCriterion("CanApprove not in", values, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveBetween(String value1, String value2) {
			addCriterion("CanApprove between", value1, value2, "canapprove");
			return (Criteria) this;
		}

		public Criteria andCanapproveNotBetween(String value1, String value2) {
			addCriterion("CanApprove not between", value1, value2, "canapprove");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeIsNull() {
			addCriterion("EmployeeCode is null");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeIsNotNull() {
			addCriterion("EmployeeCode is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeEqualTo(String value) {
			addCriterion("EmployeeCode =", value, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeNotEqualTo(String value) {
			addCriterion("EmployeeCode <>", value, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeGreaterThan(String value) {
			addCriterion("EmployeeCode >", value, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeGreaterThanOrEqualTo(String value) {
			addCriterion("EmployeeCode >=", value, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeLessThan(String value) {
			addCriterion("EmployeeCode <", value, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeLessThanOrEqualTo(String value) {
			addCriterion("EmployeeCode <=", value, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeLike(String value) {
			addCriterion("EmployeeCode like", value, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeNotLike(String value) {
			addCriterion("EmployeeCode not like", value, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeIn(List<String> values) {
			addCriterion("EmployeeCode in", values, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeNotIn(List<String> values) {
			addCriterion("EmployeeCode not in", values, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeBetween(String value1, String value2) {
			addCriterion("EmployeeCode between", value1, value2, "employeecode");
			return (Criteria) this;
		}

		public Criteria andEmployeecodeNotBetween(String value1, String value2) {
			addCriterion("EmployeeCode not between", value1, value2, "employeecode");
			return (Criteria) this;
		}

		public Criteria andPopupsIsNull() {
			addCriterion("Popups is null");
			return (Criteria) this;
		}

		public Criteria andPopupsIsNotNull() {
			addCriterion("Popups is not null");
			return (Criteria) this;
		}

		public Criteria andPopupsEqualTo(String value) {
			addCriterion("Popups =", value, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsNotEqualTo(String value) {
			addCriterion("Popups <>", value, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsGreaterThan(String value) {
			addCriterion("Popups >", value, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsGreaterThanOrEqualTo(String value) {
			addCriterion("Popups >=", value, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsLessThan(String value) {
			addCriterion("Popups <", value, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsLessThanOrEqualTo(String value) {
			addCriterion("Popups <=", value, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsLike(String value) {
			addCriterion("Popups like", value, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsNotLike(String value) {
			addCriterion("Popups not like", value, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsIn(List<String> values) {
			addCriterion("Popups in", values, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsNotIn(List<String> values) {
			addCriterion("Popups not in", values, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsBetween(String value1, String value2) {
			addCriterion("Popups between", value1, value2, "popups");
			return (Criteria) this;
		}

		public Criteria andPopupsNotBetween(String value1, String value2) {
			addCriterion("Popups not between", value1, value2, "popups");
			return (Criteria) this;
		}

		public Criteria andHidesalaryIsNull() {
			addCriterion("HideSalary is null");
			return (Criteria) this;
		}

		public Criteria andHidesalaryIsNotNull() {
			addCriterion("HideSalary is not null");
			return (Criteria) this;
		}

		public Criteria andHidesalaryEqualTo(String value) {
			addCriterion("HideSalary =", value, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryNotEqualTo(String value) {
			addCriterion("HideSalary <>", value, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryGreaterThan(String value) {
			addCriterion("HideSalary >", value, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryGreaterThanOrEqualTo(String value) {
			addCriterion("HideSalary >=", value, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryLessThan(String value) {
			addCriterion("HideSalary <", value, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryLessThanOrEqualTo(String value) {
			addCriterion("HideSalary <=", value, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryLike(String value) {
			addCriterion("HideSalary like", value, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryNotLike(String value) {
			addCriterion("HideSalary not like", value, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryIn(List<String> values) {
			addCriterion("HideSalary in", values, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryNotIn(List<String> values) {
			addCriterion("HideSalary not in", values, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryBetween(String value1, String value2) {
			addCriterion("HideSalary between", value1, value2, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andHidesalaryNotBetween(String value1, String value2) {
			addCriterion("HideSalary not between", value1, value2, "hidesalary");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolIsNull() {
			addCriterion("CheckCreditControl is null");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolIsNotNull() {
			addCriterion("CheckCreditControl is not null");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolEqualTo(String value) {
			addCriterion("CheckCreditControl =", value, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolNotEqualTo(String value) {
			addCriterion("CheckCreditControl <>", value, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolGreaterThan(String value) {
			addCriterion("CheckCreditControl >", value, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolGreaterThanOrEqualTo(String value) {
			addCriterion("CheckCreditControl >=", value, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolLessThan(String value) {
			addCriterion("CheckCreditControl <", value, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolLessThanOrEqualTo(String value) {
			addCriterion("CheckCreditControl <=", value, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolLike(String value) {
			addCriterion("CheckCreditControl like", value, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolNotLike(String value) {
			addCriterion("CheckCreditControl not like", value, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolIn(List<String> values) {
			addCriterion("CheckCreditControl in", values, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolNotIn(List<String> values) {
			addCriterion("CheckCreditControl not in", values, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolBetween(String value1, String value2) {
			addCriterion("CheckCreditControl between", value1, value2, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andCheckcreditcontrolNotBetween(String value1, String value2) {
			addCriterion("CheckCreditControl not between", value1, value2, "checkcreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolIsNull() {
			addCriterion("BypassCreditControl is null");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolIsNotNull() {
			addCriterion("BypassCreditControl is not null");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolEqualTo(String value) {
			addCriterion("BypassCreditControl =", value, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolNotEqualTo(String value) {
			addCriterion("BypassCreditControl <>", value, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolGreaterThan(String value) {
			addCriterion("BypassCreditControl >", value, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolGreaterThanOrEqualTo(String value) {
			addCriterion("BypassCreditControl >=", value, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolLessThan(String value) {
			addCriterion("BypassCreditControl <", value, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolLessThanOrEqualTo(String value) {
			addCriterion("BypassCreditControl <=", value, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolLike(String value) {
			addCriterion("BypassCreditControl like", value, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolNotLike(String value) {
			addCriterion("BypassCreditControl not like", value, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolIn(List<String> values) {
			addCriterion("BypassCreditControl in", values, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolNotIn(List<String> values) {
			addCriterion("BypassCreditControl not in", values, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolBetween(String value1, String value2) {
			addCriterion("BypassCreditControl between", value1, value2, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andBypasscreditcontrolNotBetween(String value1, String value2) {
			addCriterion("BypassCreditControl not between", value1, value2, "bypasscreditcontrol");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceIsNull() {
			addCriterion("HideCostPrice is null");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceIsNotNull() {
			addCriterion("HideCostPrice is not null");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceEqualTo(String value) {
			addCriterion("HideCostPrice =", value, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceNotEqualTo(String value) {
			addCriterion("HideCostPrice <>", value, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceGreaterThan(String value) {
			addCriterion("HideCostPrice >", value, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceGreaterThanOrEqualTo(String value) {
			addCriterion("HideCostPrice >=", value, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceLessThan(String value) {
			addCriterion("HideCostPrice <", value, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceLessThanOrEqualTo(String value) {
			addCriterion("HideCostPrice <=", value, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceLike(String value) {
			addCriterion("HideCostPrice like", value, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceNotLike(String value) {
			addCriterion("HideCostPrice not like", value, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceIn(List<String> values) {
			addCriterion("HideCostPrice in", values, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceNotIn(List<String> values) {
			addCriterion("HideCostPrice not in", values, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceBetween(String value1, String value2) {
			addCriterion("HideCostPrice between", value1, value2, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andHidecostpriceNotBetween(String value1, String value2) {
			addCriterion("HideCostPrice not between", value1, value2, "hidecostprice");
			return (Criteria) this;
		}

		public Criteria andUseesignatureIsNull() {
			addCriterion("UseESignature is null");
			return (Criteria) this;
		}

		public Criteria andUseesignatureIsNotNull() {
			addCriterion("UseESignature is not null");
			return (Criteria) this;
		}

		public Criteria andUseesignatureEqualTo(String value) {
			addCriterion("UseESignature =", value, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureNotEqualTo(String value) {
			addCriterion("UseESignature <>", value, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureGreaterThan(String value) {
			addCriterion("UseESignature >", value, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureGreaterThanOrEqualTo(String value) {
			addCriterion("UseESignature >=", value, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureLessThan(String value) {
			addCriterion("UseESignature <", value, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureLessThanOrEqualTo(String value) {
			addCriterion("UseESignature <=", value, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureLike(String value) {
			addCriterion("UseESignature like", value, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureNotLike(String value) {
			addCriterion("UseESignature not like", value, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureIn(List<String> values) {
			addCriterion("UseESignature in", values, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureNotIn(List<String> values) {
			addCriterion("UseESignature not in", values, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureBetween(String value1, String value2) {
			addCriterion("UseESignature between", value1, value2, "useesignature");
			return (Criteria) this;
		}

		public Criteria andUseesignatureNotBetween(String value1, String value2) {
			addCriterion("UseESignature not between", value1, value2, "useesignature");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsIsNull() {
			addCriterion("ChangePaymentTerms is null");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsIsNotNull() {
			addCriterion("ChangePaymentTerms is not null");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsEqualTo(String value) {
			addCriterion("ChangePaymentTerms =", value, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsNotEqualTo(String value) {
			addCriterion("ChangePaymentTerms <>", value, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsGreaterThan(String value) {
			addCriterion("ChangePaymentTerms >", value, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsGreaterThanOrEqualTo(String value) {
			addCriterion("ChangePaymentTerms >=", value, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsLessThan(String value) {
			addCriterion("ChangePaymentTerms <", value, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsLessThanOrEqualTo(String value) {
			addCriterion("ChangePaymentTerms <=", value, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsLike(String value) {
			addCriterion("ChangePaymentTerms like", value, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsNotLike(String value) {
			addCriterion("ChangePaymentTerms not like", value, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsIn(List<String> values) {
			addCriterion("ChangePaymentTerms in", values, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsNotIn(List<String> values) {
			addCriterion("ChangePaymentTerms not in", values, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsBetween(String value1, String value2) {
			addCriterion("ChangePaymentTerms between", value1, value2, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepaymenttermsNotBetween(String value1, String value2) {
			addCriterion("ChangePaymentTerms not between", value1, value2, "changepaymentterms");
			return (Criteria) this;
		}

		public Criteria andChangepriceIsNull() {
			addCriterion("ChangePrice is null");
			return (Criteria) this;
		}

		public Criteria andChangepriceIsNotNull() {
			addCriterion("ChangePrice is not null");
			return (Criteria) this;
		}

		public Criteria andChangepriceEqualTo(String value) {
			addCriterion("ChangePrice =", value, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceNotEqualTo(String value) {
			addCriterion("ChangePrice <>", value, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceGreaterThan(String value) {
			addCriterion("ChangePrice >", value, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceGreaterThanOrEqualTo(String value) {
			addCriterion("ChangePrice >=", value, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceLessThan(String value) {
			addCriterion("ChangePrice <", value, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceLessThanOrEqualTo(String value) {
			addCriterion("ChangePrice <=", value, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceLike(String value) {
			addCriterion("ChangePrice like", value, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceNotLike(String value) {
			addCriterion("ChangePrice not like", value, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceIn(List<String> values) {
			addCriterion("ChangePrice in", values, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceNotIn(List<String> values) {
			addCriterion("ChangePrice not in", values, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceBetween(String value1, String value2) {
			addCriterion("ChangePrice between", value1, value2, "changeprice");
			return (Criteria) this;
		}

		public Criteria andChangepriceNotBetween(String value1, String value2) {
			addCriterion("ChangePrice not between", value1, value2, "changeprice");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeIsNull() {
			addCriterion("HeadEmpCode is null");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeIsNotNull() {
			addCriterion("HeadEmpCode is not null");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeEqualTo(String value) {
			addCriterion("HeadEmpCode =", value, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeNotEqualTo(String value) {
			addCriterion("HeadEmpCode <>", value, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeGreaterThan(String value) {
			addCriterion("HeadEmpCode >", value, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeGreaterThanOrEqualTo(String value) {
			addCriterion("HeadEmpCode >=", value, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeLessThan(String value) {
			addCriterion("HeadEmpCode <", value, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeLessThanOrEqualTo(String value) {
			addCriterion("HeadEmpCode <=", value, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeLike(String value) {
			addCriterion("HeadEmpCode like", value, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeNotLike(String value) {
			addCriterion("HeadEmpCode not like", value, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeIn(List<String> values) {
			addCriterion("HeadEmpCode in", values, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeNotIn(List<String> values) {
			addCriterion("HeadEmpCode not in", values, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeBetween(String value1, String value2) {
			addCriterion("HeadEmpCode between", value1, value2, "headempcode");
			return (Criteria) this;
		}

		public Criteria andHeadempcodeNotBetween(String value1, String value2) {
			addCriterion("HeadEmpCode not between", value1, value2, "headempcode");
			return (Criteria) this;
		}

		public Criteria andActiveIsNull() {
			addCriterion("Active is null");
			return (Criteria) this;
		}

		public Criteria andActiveIsNotNull() {
			addCriterion("Active is not null");
			return (Criteria) this;
		}

		public Criteria andActiveEqualTo(String value) {
			addCriterion("Active =", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotEqualTo(String value) {
			addCriterion("Active <>", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThan(String value) {
			addCriterion("Active >", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThanOrEqualTo(String value) {
			addCriterion("Active >=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThan(String value) {
			addCriterion("Active <", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThanOrEqualTo(String value) {
			addCriterion("Active <=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLike(String value) {
			addCriterion("Active like", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotLike(String value) {
			addCriterion("Active not like", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveIn(List<String> values) {
			addCriterion("Active in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotIn(List<String> values) {
			addCriterion("Active not in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveBetween(String value1, String value2) {
			addCriterion("Active between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotBetween(String value1, String value2) {
			addCriterion("Active not between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andLicencealertsIsNull() {
			addCriterion("LicenceAlerts is null");
			return (Criteria) this;
		}

		public Criteria andLicencealertsIsNotNull() {
			addCriterion("LicenceAlerts is not null");
			return (Criteria) this;
		}

		public Criteria andLicencealertsEqualTo(String value) {
			addCriterion("LicenceAlerts =", value, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsNotEqualTo(String value) {
			addCriterion("LicenceAlerts <>", value, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsGreaterThan(String value) {
			addCriterion("LicenceAlerts >", value, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsGreaterThanOrEqualTo(String value) {
			addCriterion("LicenceAlerts >=", value, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsLessThan(String value) {
			addCriterion("LicenceAlerts <", value, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsLessThanOrEqualTo(String value) {
			addCriterion("LicenceAlerts <=", value, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsLike(String value) {
			addCriterion("LicenceAlerts like", value, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsNotLike(String value) {
			addCriterion("LicenceAlerts not like", value, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsIn(List<String> values) {
			addCriterion("LicenceAlerts in", values, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsNotIn(List<String> values) {
			addCriterion("LicenceAlerts not in", values, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsBetween(String value1, String value2) {
			addCriterion("LicenceAlerts between", value1, value2, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andLicencealertsNotBetween(String value1, String value2) {
			addCriterion("LicenceAlerts not between", value1, value2, "licencealerts");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynIsNull() {
			addCriterion("UnderCostSalesYN is null");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynIsNotNull() {
			addCriterion("UnderCostSalesYN is not null");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynEqualTo(String value) {
			addCriterion("UnderCostSalesYN =", value, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynNotEqualTo(String value) {
			addCriterion("UnderCostSalesYN <>", value, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynGreaterThan(String value) {
			addCriterion("UnderCostSalesYN >", value, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynGreaterThanOrEqualTo(String value) {
			addCriterion("UnderCostSalesYN >=", value, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynLessThan(String value) {
			addCriterion("UnderCostSalesYN <", value, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynLessThanOrEqualTo(String value) {
			addCriterion("UnderCostSalesYN <=", value, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynLike(String value) {
			addCriterion("UnderCostSalesYN like", value, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynNotLike(String value) {
			addCriterion("UnderCostSalesYN not like", value, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynIn(List<String> values) {
			addCriterion("UnderCostSalesYN in", values, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynNotIn(List<String> values) {
			addCriterion("UnderCostSalesYN not in", values, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynBetween(String value1, String value2) {
			addCriterion("UnderCostSalesYN between", value1, value2, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andUndercostsalesynNotBetween(String value1, String value2) {
			addCriterion("UnderCostSalesYN not between", value1, value2, "undercostsalesyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynIsNull() {
			addCriterion("SetPriceMatrixYN is null");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynIsNotNull() {
			addCriterion("SetPriceMatrixYN is not null");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynEqualTo(String value) {
			addCriterion("SetPriceMatrixYN =", value, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynNotEqualTo(String value) {
			addCriterion("SetPriceMatrixYN <>", value, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynGreaterThan(String value) {
			addCriterion("SetPriceMatrixYN >", value, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynGreaterThanOrEqualTo(String value) {
			addCriterion("SetPriceMatrixYN >=", value, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynLessThan(String value) {
			addCriterion("SetPriceMatrixYN <", value, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynLessThanOrEqualTo(String value) {
			addCriterion("SetPriceMatrixYN <=", value, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynLike(String value) {
			addCriterion("SetPriceMatrixYN like", value, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynNotLike(String value) {
			addCriterion("SetPriceMatrixYN not like", value, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynIn(List<String> values) {
			addCriterion("SetPriceMatrixYN in", values, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynNotIn(List<String> values) {
			addCriterion("SetPriceMatrixYN not in", values, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynBetween(String value1, String value2) {
			addCriterion("SetPriceMatrixYN between", value1, value2, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andSetpricematrixynNotBetween(String value1, String value2) {
			addCriterion("SetPriceMatrixYN not between", value1, value2, "setpricematrixyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynIsNull() {
			addCriterion("CostSalesYN is null");
			return (Criteria) this;
		}

		public Criteria andCostsalesynIsNotNull() {
			addCriterion("CostSalesYN is not null");
			return (Criteria) this;
		}

		public Criteria andCostsalesynEqualTo(String value) {
			addCriterion("CostSalesYN =", value, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynNotEqualTo(String value) {
			addCriterion("CostSalesYN <>", value, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynGreaterThan(String value) {
			addCriterion("CostSalesYN >", value, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynGreaterThanOrEqualTo(String value) {
			addCriterion("CostSalesYN >=", value, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynLessThan(String value) {
			addCriterion("CostSalesYN <", value, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynLessThanOrEqualTo(String value) {
			addCriterion("CostSalesYN <=", value, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynLike(String value) {
			addCriterion("CostSalesYN like", value, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynNotLike(String value) {
			addCriterion("CostSalesYN not like", value, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynIn(List<String> values) {
			addCriterion("CostSalesYN in", values, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynNotIn(List<String> values) {
			addCriterion("CostSalesYN not in", values, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynBetween(String value1, String value2) {
			addCriterion("CostSalesYN between", value1, value2, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andCostsalesynNotBetween(String value1, String value2) {
			addCriterion("CostSalesYN not between", value1, value2, "costsalesyn");
			return (Criteria) this;
		}

		public Criteria andThemeIsNull() {
			addCriterion("Theme is null");
			return (Criteria) this;
		}

		public Criteria andThemeIsNotNull() {
			addCriterion("Theme is not null");
			return (Criteria) this;
		}

		public Criteria andThemeEqualTo(String value) {
			addCriterion("Theme =", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotEqualTo(String value) {
			addCriterion("Theme <>", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeGreaterThan(String value) {
			addCriterion("Theme >", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeGreaterThanOrEqualTo(String value) {
			addCriterion("Theme >=", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeLessThan(String value) {
			addCriterion("Theme <", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeLessThanOrEqualTo(String value) {
			addCriterion("Theme <=", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeLike(String value) {
			addCriterion("Theme like", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotLike(String value) {
			addCriterion("Theme not like", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeIn(List<String> values) {
			addCriterion("Theme in", values, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotIn(List<String> values) {
			addCriterion("Theme not in", values, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeBetween(String value1, String value2) {
			addCriterion("Theme between", value1, value2, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotBetween(String value1, String value2) {
			addCriterion("Theme not between", value1, value2, "theme");
			return (Criteria) this;
		}

		public Criteria andWorkingdocIsNull() {
			addCriterion("WorkingDoc is null");
			return (Criteria) this;
		}

		public Criteria andWorkingdocIsNotNull() {
			addCriterion("WorkingDoc is not null");
			return (Criteria) this;
		}

		public Criteria andWorkingdocEqualTo(String value) {
			addCriterion("WorkingDoc =", value, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocNotEqualTo(String value) {
			addCriterion("WorkingDoc <>", value, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocGreaterThan(String value) {
			addCriterion("WorkingDoc >", value, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocGreaterThanOrEqualTo(String value) {
			addCriterion("WorkingDoc >=", value, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocLessThan(String value) {
			addCriterion("WorkingDoc <", value, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocLessThanOrEqualTo(String value) {
			addCriterion("WorkingDoc <=", value, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocLike(String value) {
			addCriterion("WorkingDoc like", value, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocNotLike(String value) {
			addCriterion("WorkingDoc not like", value, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocIn(List<String> values) {
			addCriterion("WorkingDoc in", values, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocNotIn(List<String> values) {
			addCriterion("WorkingDoc not in", values, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocBetween(String value1, String value2) {
			addCriterion("WorkingDoc between", value1, value2, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andWorkingdocNotBetween(String value1, String value2) {
			addCriterion("WorkingDoc not between", value1, value2, "workingdoc");
			return (Criteria) this;
		}

		public Criteria andResetloginIsNull() {
			addCriterion("ResetLogin is null");
			return (Criteria) this;
		}

		public Criteria andResetloginIsNotNull() {
			addCriterion("ResetLogin is not null");
			return (Criteria) this;
		}

		public Criteria andResetloginEqualTo(String value) {
			addCriterion("ResetLogin =", value, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginNotEqualTo(String value) {
			addCriterion("ResetLogin <>", value, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginGreaterThan(String value) {
			addCriterion("ResetLogin >", value, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginGreaterThanOrEqualTo(String value) {
			addCriterion("ResetLogin >=", value, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginLessThan(String value) {
			addCriterion("ResetLogin <", value, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginLessThanOrEqualTo(String value) {
			addCriterion("ResetLogin <=", value, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginLike(String value) {
			addCriterion("ResetLogin like", value, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginNotLike(String value) {
			addCriterion("ResetLogin not like", value, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginIn(List<String> values) {
			addCriterion("ResetLogin in", values, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginNotIn(List<String> values) {
			addCriterion("ResetLogin not in", values, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginBetween(String value1, String value2) {
			addCriterion("ResetLogin between", value1, value2, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andResetloginNotBetween(String value1, String value2) {
			addCriterion("ResetLogin not between", value1, value2, "resetlogin");
			return (Criteria) this;
		}

		public Criteria andSysnameIsNull() {
			addCriterion("SysName is null");
			return (Criteria) this;
		}

		public Criteria andSysnameIsNotNull() {
			addCriterion("SysName is not null");
			return (Criteria) this;
		}

		public Criteria andSysnameEqualTo(String value) {
			addCriterion("SysName =", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameNotEqualTo(String value) {
			addCriterion("SysName <>", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameGreaterThan(String value) {
			addCriterion("SysName >", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameGreaterThanOrEqualTo(String value) {
			addCriterion("SysName >=", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameLessThan(String value) {
			addCriterion("SysName <", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameLessThanOrEqualTo(String value) {
			addCriterion("SysName <=", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameLike(String value) {
			addCriterion("SysName like", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameNotLike(String value) {
			addCriterion("SysName not like", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameIn(List<String> values) {
			addCriterion("SysName in", values, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameNotIn(List<String> values) {
			addCriterion("SysName not in", values, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameBetween(String value1, String value2) {
			addCriterion("SysName between", value1, value2, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameNotBetween(String value1, String value2) {
			addCriterion("SysName not between", value1, value2, "sysname");
			return (Criteria) this;
		}

		public Criteria andLastlogindateIsNull() {
			addCriterion("LastLoginDate is null");
			return (Criteria) this;
		}

		public Criteria andLastlogindateIsNotNull() {
			addCriterion("LastLoginDate is not null");
			return (Criteria) this;
		}

		public Criteria andLastlogindateEqualTo(Date value) {
			addCriterion("LastLoginDate =", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateNotEqualTo(Date value) {
			addCriterion("LastLoginDate <>", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateGreaterThan(Date value) {
			addCriterion("LastLoginDate >", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateGreaterThanOrEqualTo(Date value) {
			addCriterion("LastLoginDate >=", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateLessThan(Date value) {
			addCriterion("LastLoginDate <", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateLessThanOrEqualTo(Date value) {
			addCriterion("LastLoginDate <=", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateIn(List<Date> values) {
			addCriterion("LastLoginDate in", values, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateNotIn(List<Date> values) {
			addCriterion("LastLoginDate not in", values, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateBetween(Date value1, Date value2) {
			addCriterion("LastLoginDate between", value1, value2, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateNotBetween(Date value1, Date value2) {
			addCriterion("LastLoginDate not between", value1, value2, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastloginsysIsNull() {
			addCriterion("Lastloginsys is null");
			return (Criteria) this;
		}

		public Criteria andLastloginsysIsNotNull() {
			addCriterion("Lastloginsys is not null");
			return (Criteria) this;
		}

		public Criteria andLastloginsysEqualTo(String value) {
			addCriterion("Lastloginsys =", value, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysNotEqualTo(String value) {
			addCriterion("Lastloginsys <>", value, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysGreaterThan(String value) {
			addCriterion("Lastloginsys >", value, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysGreaterThanOrEqualTo(String value) {
			addCriterion("Lastloginsys >=", value, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysLessThan(String value) {
			addCriterion("Lastloginsys <", value, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysLessThanOrEqualTo(String value) {
			addCriterion("Lastloginsys <=", value, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysLike(String value) {
			addCriterion("Lastloginsys like", value, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysNotLike(String value) {
			addCriterion("Lastloginsys not like", value, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysIn(List<String> values) {
			addCriterion("Lastloginsys in", values, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysNotIn(List<String> values) {
			addCriterion("Lastloginsys not in", values, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysBetween(String value1, String value2) {
			addCriterion("Lastloginsys between", value1, value2, "lastloginsys");
			return (Criteria) this;
		}

		public Criteria andLastloginsysNotBetween(String value1, String value2) {
			addCriterion("Lastloginsys not between", value1, value2, "lastloginsys");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TBADAPA0016
	 * @mbg.generated  Sun Dec 09 14:43:14 GST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.TBADAPA0016
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 09 13:35:59 GST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}