package com.awf.model.orm.dbo;

import java.util.Date;

public class WFContent extends WFContentKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFContent.FileName
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String filename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFContent.FileRef
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String fileref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFContent.LastModifiedon
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date lastmodifiedon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFContent.FileExtension
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String fileextension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFContent.FileSize
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String filesize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFContent.FilePath
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String filepath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFContent.Visibility
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String visibility;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFContent.AddedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String addedby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFContent.Addedon
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date addedon;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFContent.FileName
	 * @return  the value of dbo.WFContent.FileName
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFContent.FileName
	 * @param filename  the value for dbo.WFContent.FileName
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setFilename(String filename) {
		this.filename = filename == null ? null : filename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFContent.FileRef
	 * @return  the value of dbo.WFContent.FileRef
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getFileref() {
		return fileref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFContent.FileRef
	 * @param fileref  the value for dbo.WFContent.FileRef
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setFileref(String fileref) {
		this.fileref = fileref == null ? null : fileref.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFContent.LastModifiedon
	 * @return  the value of dbo.WFContent.LastModifiedon
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getLastmodifiedon() {
		return lastmodifiedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFContent.LastModifiedon
	 * @param lastmodifiedon  the value for dbo.WFContent.LastModifiedon
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setLastmodifiedon(Date lastmodifiedon) {
		this.lastmodifiedon = lastmodifiedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFContent.FileExtension
	 * @return  the value of dbo.WFContent.FileExtension
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getFileextension() {
		return fileextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFContent.FileExtension
	 * @param fileextension  the value for dbo.WFContent.FileExtension
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setFileextension(String fileextension) {
		this.fileextension = fileextension == null ? null : fileextension.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFContent.FileSize
	 * @return  the value of dbo.WFContent.FileSize
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getFilesize() {
		return filesize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFContent.FileSize
	 * @param filesize  the value for dbo.WFContent.FileSize
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setFilesize(String filesize) {
		this.filesize = filesize == null ? null : filesize.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFContent.FilePath
	 * @return  the value of dbo.WFContent.FilePath
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getFilepath() {
		return filepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFContent.FilePath
	 * @param filepath  the value for dbo.WFContent.FilePath
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setFilepath(String filepath) {
		this.filepath = filepath == null ? null : filepath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFContent.Visibility
	 * @return  the value of dbo.WFContent.Visibility
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getVisibility() {
		return visibility;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFContent.Visibility
	 * @param visibility  the value for dbo.WFContent.Visibility
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setVisibility(String visibility) {
		this.visibility = visibility == null ? null : visibility.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFContent.AddedBy
	 * @return  the value of dbo.WFContent.AddedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getAddedby() {
		return addedby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFContent.AddedBy
	 * @param addedby  the value for dbo.WFContent.AddedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setAddedby(String addedby) {
		this.addedby = addedby == null ? null : addedby.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFContent.Addedon
	 * @return  the value of dbo.WFContent.Addedon
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getAddedon() {
		return addedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFContent.Addedon
	 * @param addedon  the value for dbo.WFContent.Addedon
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setAddedon(Date addedon) {
		this.addedon = addedon;
	}
}