package com.awf.model.orm.dbo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WFContentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public WFContentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodeIsNull() {
			addCriterion("Code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("Code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(Long value) {
			addCriterion("Code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(Long value) {
			addCriterion("Code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(Long value) {
			addCriterion("Code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(Long value) {
			addCriterion("Code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(Long value) {
			addCriterion("Code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(Long value) {
			addCriterion("Code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<Long> values) {
			addCriterion("Code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<Long> values) {
			addCriterion("Code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(Long value1, Long value2) {
			addCriterion("Code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(Long value1, Long value2) {
			addCriterion("Code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andStepcodeIsNull() {
			addCriterion("StepCode is null");
			return (Criteria) this;
		}

		public Criteria andStepcodeIsNotNull() {
			addCriterion("StepCode is not null");
			return (Criteria) this;
		}

		public Criteria andStepcodeEqualTo(String value) {
			addCriterion("StepCode =", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeNotEqualTo(String value) {
			addCriterion("StepCode <>", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeGreaterThan(String value) {
			addCriterion("StepCode >", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeGreaterThanOrEqualTo(String value) {
			addCriterion("StepCode >=", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeLessThan(String value) {
			addCriterion("StepCode <", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeLessThanOrEqualTo(String value) {
			addCriterion("StepCode <=", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeLike(String value) {
			addCriterion("StepCode like", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeNotLike(String value) {
			addCriterion("StepCode not like", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeIn(List<String> values) {
			addCriterion("StepCode in", values, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeNotIn(List<String> values) {
			addCriterion("StepCode not in", values, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeBetween(String value1, String value2) {
			addCriterion("StepCode between", value1, value2, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeNotBetween(String value1, String value2) {
			addCriterion("StepCode not between", value1, value2, "stepcode");
			return (Criteria) this;
		}

		public Criteria andSerialnoIsNull() {
			addCriterion("SerialNo is null");
			return (Criteria) this;
		}

		public Criteria andSerialnoIsNotNull() {
			addCriterion("SerialNo is not null");
			return (Criteria) this;
		}

		public Criteria andSerialnoEqualTo(Integer value) {
			addCriterion("SerialNo =", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotEqualTo(Integer value) {
			addCriterion("SerialNo <>", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoGreaterThan(Integer value) {
			addCriterion("SerialNo >", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoGreaterThanOrEqualTo(Integer value) {
			addCriterion("SerialNo >=", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoLessThan(Integer value) {
			addCriterion("SerialNo <", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoLessThanOrEqualTo(Integer value) {
			addCriterion("SerialNo <=", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoIn(List<Integer> values) {
			addCriterion("SerialNo in", values, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotIn(List<Integer> values) {
			addCriterion("SerialNo not in", values, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoBetween(Integer value1, Integer value2) {
			addCriterion("SerialNo between", value1, value2, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotBetween(Integer value1, Integer value2) {
			addCriterion("SerialNo not between", value1, value2, "serialno");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("Type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("Type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("Type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("Type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("Type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("Type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("Type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("Type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("Type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("Type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("Type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("Type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("Type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("Type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andFilenameIsNull() {
			addCriterion("FileName is null");
			return (Criteria) this;
		}

		public Criteria andFilenameIsNotNull() {
			addCriterion("FileName is not null");
			return (Criteria) this;
		}

		public Criteria andFilenameEqualTo(String value) {
			addCriterion("FileName =", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameNotEqualTo(String value) {
			addCriterion("FileName <>", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameGreaterThan(String value) {
			addCriterion("FileName >", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameGreaterThanOrEqualTo(String value) {
			addCriterion("FileName >=", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameLessThan(String value) {
			addCriterion("FileName <", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameLessThanOrEqualTo(String value) {
			addCriterion("FileName <=", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameLike(String value) {
			addCriterion("FileName like", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameNotLike(String value) {
			addCriterion("FileName not like", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameIn(List<String> values) {
			addCriterion("FileName in", values, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameNotIn(List<String> values) {
			addCriterion("FileName not in", values, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameBetween(String value1, String value2) {
			addCriterion("FileName between", value1, value2, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameNotBetween(String value1, String value2) {
			addCriterion("FileName not between", value1, value2, "filename");
			return (Criteria) this;
		}

		public Criteria andFilerefIsNull() {
			addCriterion("FileRef is null");
			return (Criteria) this;
		}

		public Criteria andFilerefIsNotNull() {
			addCriterion("FileRef is not null");
			return (Criteria) this;
		}

		public Criteria andFilerefEqualTo(String value) {
			addCriterion("FileRef =", value, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefNotEqualTo(String value) {
			addCriterion("FileRef <>", value, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefGreaterThan(String value) {
			addCriterion("FileRef >", value, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefGreaterThanOrEqualTo(String value) {
			addCriterion("FileRef >=", value, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefLessThan(String value) {
			addCriterion("FileRef <", value, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefLessThanOrEqualTo(String value) {
			addCriterion("FileRef <=", value, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefLike(String value) {
			addCriterion("FileRef like", value, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefNotLike(String value) {
			addCriterion("FileRef not like", value, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefIn(List<String> values) {
			addCriterion("FileRef in", values, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefNotIn(List<String> values) {
			addCriterion("FileRef not in", values, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefBetween(String value1, String value2) {
			addCriterion("FileRef between", value1, value2, "fileref");
			return (Criteria) this;
		}

		public Criteria andFilerefNotBetween(String value1, String value2) {
			addCriterion("FileRef not between", value1, value2, "fileref");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonIsNull() {
			addCriterion("LastModifiedon is null");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonIsNotNull() {
			addCriterion("LastModifiedon is not null");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonEqualTo(Date value) {
			addCriterion("LastModifiedon =", value, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonNotEqualTo(Date value) {
			addCriterion("LastModifiedon <>", value, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonGreaterThan(Date value) {
			addCriterion("LastModifiedon >", value, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonGreaterThanOrEqualTo(Date value) {
			addCriterion("LastModifiedon >=", value, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonLessThan(Date value) {
			addCriterion("LastModifiedon <", value, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonLessThanOrEqualTo(Date value) {
			addCriterion("LastModifiedon <=", value, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonIn(List<Date> values) {
			addCriterion("LastModifiedon in", values, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonNotIn(List<Date> values) {
			addCriterion("LastModifiedon not in", values, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonBetween(Date value1, Date value2) {
			addCriterion("LastModifiedon between", value1, value2, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andLastmodifiedonNotBetween(Date value1, Date value2) {
			addCriterion("LastModifiedon not between", value1, value2, "lastmodifiedon");
			return (Criteria) this;
		}

		public Criteria andFileextensionIsNull() {
			addCriterion("FileExtension is null");
			return (Criteria) this;
		}

		public Criteria andFileextensionIsNotNull() {
			addCriterion("FileExtension is not null");
			return (Criteria) this;
		}

		public Criteria andFileextensionEqualTo(String value) {
			addCriterion("FileExtension =", value, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionNotEqualTo(String value) {
			addCriterion("FileExtension <>", value, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionGreaterThan(String value) {
			addCriterion("FileExtension >", value, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionGreaterThanOrEqualTo(String value) {
			addCriterion("FileExtension >=", value, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionLessThan(String value) {
			addCriterion("FileExtension <", value, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionLessThanOrEqualTo(String value) {
			addCriterion("FileExtension <=", value, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionLike(String value) {
			addCriterion("FileExtension like", value, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionNotLike(String value) {
			addCriterion("FileExtension not like", value, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionIn(List<String> values) {
			addCriterion("FileExtension in", values, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionNotIn(List<String> values) {
			addCriterion("FileExtension not in", values, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionBetween(String value1, String value2) {
			addCriterion("FileExtension between", value1, value2, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFileextensionNotBetween(String value1, String value2) {
			addCriterion("FileExtension not between", value1, value2, "fileextension");
			return (Criteria) this;
		}

		public Criteria andFilesizeIsNull() {
			addCriterion("FileSize is null");
			return (Criteria) this;
		}

		public Criteria andFilesizeIsNotNull() {
			addCriterion("FileSize is not null");
			return (Criteria) this;
		}

		public Criteria andFilesizeEqualTo(String value) {
			addCriterion("FileSize =", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeNotEqualTo(String value) {
			addCriterion("FileSize <>", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeGreaterThan(String value) {
			addCriterion("FileSize >", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeGreaterThanOrEqualTo(String value) {
			addCriterion("FileSize >=", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeLessThan(String value) {
			addCriterion("FileSize <", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeLessThanOrEqualTo(String value) {
			addCriterion("FileSize <=", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeLike(String value) {
			addCriterion("FileSize like", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeNotLike(String value) {
			addCriterion("FileSize not like", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeIn(List<String> values) {
			addCriterion("FileSize in", values, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeNotIn(List<String> values) {
			addCriterion("FileSize not in", values, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeBetween(String value1, String value2) {
			addCriterion("FileSize between", value1, value2, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeNotBetween(String value1, String value2) {
			addCriterion("FileSize not between", value1, value2, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilepathIsNull() {
			addCriterion("FilePath is null");
			return (Criteria) this;
		}

		public Criteria andFilepathIsNotNull() {
			addCriterion("FilePath is not null");
			return (Criteria) this;
		}

		public Criteria andFilepathEqualTo(String value) {
			addCriterion("FilePath =", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathNotEqualTo(String value) {
			addCriterion("FilePath <>", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathGreaterThan(String value) {
			addCriterion("FilePath >", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathGreaterThanOrEqualTo(String value) {
			addCriterion("FilePath >=", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathLessThan(String value) {
			addCriterion("FilePath <", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathLessThanOrEqualTo(String value) {
			addCriterion("FilePath <=", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathLike(String value) {
			addCriterion("FilePath like", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathNotLike(String value) {
			addCriterion("FilePath not like", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathIn(List<String> values) {
			addCriterion("FilePath in", values, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathNotIn(List<String> values) {
			addCriterion("FilePath not in", values, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathBetween(String value1, String value2) {
			addCriterion("FilePath between", value1, value2, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathNotBetween(String value1, String value2) {
			addCriterion("FilePath not between", value1, value2, "filepath");
			return (Criteria) this;
		}

		public Criteria andVisibilityIsNull() {
			addCriterion("Visibility is null");
			return (Criteria) this;
		}

		public Criteria andVisibilityIsNotNull() {
			addCriterion("Visibility is not null");
			return (Criteria) this;
		}

		public Criteria andVisibilityEqualTo(String value) {
			addCriterion("Visibility =", value, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityNotEqualTo(String value) {
			addCriterion("Visibility <>", value, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityGreaterThan(String value) {
			addCriterion("Visibility >", value, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityGreaterThanOrEqualTo(String value) {
			addCriterion("Visibility >=", value, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityLessThan(String value) {
			addCriterion("Visibility <", value, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityLessThanOrEqualTo(String value) {
			addCriterion("Visibility <=", value, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityLike(String value) {
			addCriterion("Visibility like", value, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityNotLike(String value) {
			addCriterion("Visibility not like", value, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityIn(List<String> values) {
			addCriterion("Visibility in", values, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityNotIn(List<String> values) {
			addCriterion("Visibility not in", values, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityBetween(String value1, String value2) {
			addCriterion("Visibility between", value1, value2, "visibility");
			return (Criteria) this;
		}

		public Criteria andVisibilityNotBetween(String value1, String value2) {
			addCriterion("Visibility not between", value1, value2, "visibility");
			return (Criteria) this;
		}

		public Criteria andAddedbyIsNull() {
			addCriterion("AddedBy is null");
			return (Criteria) this;
		}

		public Criteria andAddedbyIsNotNull() {
			addCriterion("AddedBy is not null");
			return (Criteria) this;
		}

		public Criteria andAddedbyEqualTo(String value) {
			addCriterion("AddedBy =", value, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyNotEqualTo(String value) {
			addCriterion("AddedBy <>", value, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyGreaterThan(String value) {
			addCriterion("AddedBy >", value, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyGreaterThanOrEqualTo(String value) {
			addCriterion("AddedBy >=", value, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyLessThan(String value) {
			addCriterion("AddedBy <", value, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyLessThanOrEqualTo(String value) {
			addCriterion("AddedBy <=", value, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyLike(String value) {
			addCriterion("AddedBy like", value, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyNotLike(String value) {
			addCriterion("AddedBy not like", value, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyIn(List<String> values) {
			addCriterion("AddedBy in", values, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyNotIn(List<String> values) {
			addCriterion("AddedBy not in", values, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyBetween(String value1, String value2) {
			addCriterion("AddedBy between", value1, value2, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedbyNotBetween(String value1, String value2) {
			addCriterion("AddedBy not between", value1, value2, "addedby");
			return (Criteria) this;
		}

		public Criteria andAddedonIsNull() {
			addCriterion("Addedon is null");
			return (Criteria) this;
		}

		public Criteria andAddedonIsNotNull() {
			addCriterion("Addedon is not null");
			return (Criteria) this;
		}

		public Criteria andAddedonEqualTo(Date value) {
			addCriterion("Addedon =", value, "addedon");
			return (Criteria) this;
		}

		public Criteria andAddedonNotEqualTo(Date value) {
			addCriterion("Addedon <>", value, "addedon");
			return (Criteria) this;
		}

		public Criteria andAddedonGreaterThan(Date value) {
			addCriterion("Addedon >", value, "addedon");
			return (Criteria) this;
		}

		public Criteria andAddedonGreaterThanOrEqualTo(Date value) {
			addCriterion("Addedon >=", value, "addedon");
			return (Criteria) this;
		}

		public Criteria andAddedonLessThan(Date value) {
			addCriterion("Addedon <", value, "addedon");
			return (Criteria) this;
		}

		public Criteria andAddedonLessThanOrEqualTo(Date value) {
			addCriterion("Addedon <=", value, "addedon");
			return (Criteria) this;
		}

		public Criteria andAddedonIn(List<Date> values) {
			addCriterion("Addedon in", values, "addedon");
			return (Criteria) this;
		}

		public Criteria andAddedonNotIn(List<Date> values) {
			addCriterion("Addedon not in", values, "addedon");
			return (Criteria) this;
		}

		public Criteria andAddedonBetween(Date value1, Date value2) {
			addCriterion("Addedon between", value1, value2, "addedon");
			return (Criteria) this;
		}

		public Criteria andAddedonNotBetween(Date value1, Date value2) {
			addCriterion("Addedon not between", value1, value2, "addedon");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.WFContent
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 02 15:26:01 GST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}