package com.awf.model.orm.dbo;

import java.util.Date;

public class WFMaster {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.StepSequence
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String stepsequence;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.Title
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.AppliesTo
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String appliesto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.Flow
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String flow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.Status
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.StartDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date startdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.EndDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date enddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.StepCount
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Integer stepcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.Rating
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Integer rating;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.Percentage
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Integer percentage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.CreatedDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date createddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.CreatedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String createdby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.RefNumber
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String refnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFMaster.Description
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.StepSequence
	 * @return  the value of dbo.WFMaster.StepSequence
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getStepsequence() {
		return stepsequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.StepSequence
	 * @param stepsequence  the value for dbo.WFMaster.StepSequence
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setStepsequence(String stepsequence) {
		this.stepsequence = stepsequence == null ? null : stepsequence.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.Title
	 * @return  the value of dbo.WFMaster.Title
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.Title
	 * @param title  the value for dbo.WFMaster.Title
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.AppliesTo
	 * @return  the value of dbo.WFMaster.AppliesTo
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getAppliesto() {
		return appliesto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.AppliesTo
	 * @param appliesto  the value for dbo.WFMaster.AppliesTo
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setAppliesto(String appliesto) {
		this.appliesto = appliesto == null ? null : appliesto.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.Flow
	 * @return  the value of dbo.WFMaster.Flow
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getFlow() {
		return flow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.Flow
	 * @param flow  the value for dbo.WFMaster.Flow
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setFlow(String flow) {
		this.flow = flow == null ? null : flow.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.Status
	 * @return  the value of dbo.WFMaster.Status
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.Status
	 * @param status  the value for dbo.WFMaster.Status
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.StartDate
	 * @return  the value of dbo.WFMaster.StartDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getStartdate() {
		return startdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.StartDate
	 * @param startdate  the value for dbo.WFMaster.StartDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.EndDate
	 * @return  the value of dbo.WFMaster.EndDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getEnddate() {
		return enddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.EndDate
	 * @param enddate  the value for dbo.WFMaster.EndDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.StepCount
	 * @return  the value of dbo.WFMaster.StepCount
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Integer getStepcount() {
		return stepcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.StepCount
	 * @param stepcount  the value for dbo.WFMaster.StepCount
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setStepcount(Integer stepcount) {
		this.stepcount = stepcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.Rating
	 * @return  the value of dbo.WFMaster.Rating
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Integer getRating() {
		return rating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.Rating
	 * @param rating  the value for dbo.WFMaster.Rating
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setRating(Integer rating) {
		this.rating = rating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.Percentage
	 * @return  the value of dbo.WFMaster.Percentage
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Integer getPercentage() {
		return percentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.Percentage
	 * @param percentage  the value for dbo.WFMaster.Percentage
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setPercentage(Integer percentage) {
		this.percentage = percentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.CreatedDate
	 * @return  the value of dbo.WFMaster.CreatedDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getCreateddate() {
		return createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.CreatedDate
	 * @param createddate  the value for dbo.WFMaster.CreatedDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.CreatedBy
	 * @return  the value of dbo.WFMaster.CreatedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getCreatedby() {
		return createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.CreatedBy
	 * @param createdby  the value for dbo.WFMaster.CreatedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setCreatedby(String createdby) {
		this.createdby = createdby == null ? null : createdby.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.RefNumber
	 * @return  the value of dbo.WFMaster.RefNumber
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getRefnumber() {
		return refnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.RefNumber
	 * @param refnumber  the value for dbo.WFMaster.RefNumber
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setRefnumber(String refnumber) {
		this.refnumber = refnumber == null ? null : refnumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFMaster.Description
	 * @return  the value of dbo.WFMaster.Description
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFMaster.Description
	 * @param description  the value for dbo.WFMaster.Description
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}