package com.awf.model.orm.dbo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class WFMasterExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public WFMasterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andStepsequenceIsNull() {
			addCriterion("StepSequence is null");
			return (Criteria) this;
		}

		public Criteria andStepsequenceIsNotNull() {
			addCriterion("StepSequence is not null");
			return (Criteria) this;
		}

		public Criteria andStepsequenceEqualTo(String value) {
			addCriterion("StepSequence =", value, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceNotEqualTo(String value) {
			addCriterion("StepSequence <>", value, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceGreaterThan(String value) {
			addCriterion("StepSequence >", value, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceGreaterThanOrEqualTo(String value) {
			addCriterion("StepSequence >=", value, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceLessThan(String value) {
			addCriterion("StepSequence <", value, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceLessThanOrEqualTo(String value) {
			addCriterion("StepSequence <=", value, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceLike(String value) {
			addCriterion("StepSequence like", value, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceNotLike(String value) {
			addCriterion("StepSequence not like", value, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceIn(List<String> values) {
			addCriterion("StepSequence in", values, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceNotIn(List<String> values) {
			addCriterion("StepSequence not in", values, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceBetween(String value1, String value2) {
			addCriterion("StepSequence between", value1, value2, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andStepsequenceNotBetween(String value1, String value2) {
			addCriterion("StepSequence not between", value1, value2, "stepsequence");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("Title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("Title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("Title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("Title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("Title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("Title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("Title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("Title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("Title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("Title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("Title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("Title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("Title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("Title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andAppliestoIsNull() {
			addCriterion("AppliesTo is null");
			return (Criteria) this;
		}

		public Criteria andAppliestoIsNotNull() {
			addCriterion("AppliesTo is not null");
			return (Criteria) this;
		}

		public Criteria andAppliestoEqualTo(String value) {
			addCriterion("AppliesTo =", value, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoNotEqualTo(String value) {
			addCriterion("AppliesTo <>", value, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoGreaterThan(String value) {
			addCriterion("AppliesTo >", value, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoGreaterThanOrEqualTo(String value) {
			addCriterion("AppliesTo >=", value, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoLessThan(String value) {
			addCriterion("AppliesTo <", value, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoLessThanOrEqualTo(String value) {
			addCriterion("AppliesTo <=", value, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoLike(String value) {
			addCriterion("AppliesTo like", value, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoNotLike(String value) {
			addCriterion("AppliesTo not like", value, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoIn(List<String> values) {
			addCriterion("AppliesTo in", values, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoNotIn(List<String> values) {
			addCriterion("AppliesTo not in", values, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoBetween(String value1, String value2) {
			addCriterion("AppliesTo between", value1, value2, "appliesto");
			return (Criteria) this;
		}

		public Criteria andAppliestoNotBetween(String value1, String value2) {
			addCriterion("AppliesTo not between", value1, value2, "appliesto");
			return (Criteria) this;
		}

		public Criteria andFlowIsNull() {
			addCriterion("Flow is null");
			return (Criteria) this;
		}

		public Criteria andFlowIsNotNull() {
			addCriterion("Flow is not null");
			return (Criteria) this;
		}

		public Criteria andFlowEqualTo(String value) {
			addCriterion("Flow =", value, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowNotEqualTo(String value) {
			addCriterion("Flow <>", value, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowGreaterThan(String value) {
			addCriterion("Flow >", value, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowGreaterThanOrEqualTo(String value) {
			addCriterion("Flow >=", value, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowLessThan(String value) {
			addCriterion("Flow <", value, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowLessThanOrEqualTo(String value) {
			addCriterion("Flow <=", value, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowLike(String value) {
			addCriterion("Flow like", value, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowNotLike(String value) {
			addCriterion("Flow not like", value, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowIn(List<String> values) {
			addCriterion("Flow in", values, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowNotIn(List<String> values) {
			addCriterion("Flow not in", values, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowBetween(String value1, String value2) {
			addCriterion("Flow between", value1, value2, "flow");
			return (Criteria) this;
		}

		public Criteria andFlowNotBetween(String value1, String value2) {
			addCriterion("Flow not between", value1, value2, "flow");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("Status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("Status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("Status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("Status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("Status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("Status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("Status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("Status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("Status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("Status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("Status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("Status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("Status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("Status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStartdateIsNull() {
			addCriterion("StartDate is null");
			return (Criteria) this;
		}

		public Criteria andStartdateIsNotNull() {
			addCriterion("StartDate is not null");
			return (Criteria) this;
		}

		public Criteria andStartdateEqualTo(Date value) {
			addCriterion("StartDate =", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateNotEqualTo(Date value) {
			addCriterion("StartDate <>", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateGreaterThan(Date value) {
			addCriterion("StartDate >", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
			addCriterion("StartDate >=", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateLessThan(Date value) {
			addCriterion("StartDate <", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateLessThanOrEqualTo(Date value) {
			addCriterion("StartDate <=", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateIn(List<Date> values) {
			addCriterion("StartDate in", values, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateNotIn(List<Date> values) {
			addCriterion("StartDate not in", values, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateBetween(Date value1, Date value2) {
			addCriterion("StartDate between", value1, value2, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateNotBetween(Date value1, Date value2) {
			addCriterion("StartDate not between", value1, value2, "startdate");
			return (Criteria) this;
		}

		public Criteria andEnddateIsNull() {
			addCriterion("EndDate is null");
			return (Criteria) this;
		}

		public Criteria andEnddateIsNotNull() {
			addCriterion("EndDate is not null");
			return (Criteria) this;
		}

		public Criteria andEnddateEqualTo(Date value) {
			addCriterion("EndDate =", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateNotEqualTo(Date value) {
			addCriterion("EndDate <>", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateGreaterThan(Date value) {
			addCriterion("EndDate >", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
			addCriterion("EndDate >=", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateLessThan(Date value) {
			addCriterion("EndDate <", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateLessThanOrEqualTo(Date value) {
			addCriterion("EndDate <=", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateIn(List<Date> values) {
			addCriterion("EndDate in", values, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateNotIn(List<Date> values) {
			addCriterion("EndDate not in", values, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateBetween(Date value1, Date value2) {
			addCriterion("EndDate between", value1, value2, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateNotBetween(Date value1, Date value2) {
			addCriterion("EndDate not between", value1, value2, "enddate");
			return (Criteria) this;
		}

		public Criteria andStepcountIsNull() {
			addCriterion("StepCount is null");
			return (Criteria) this;
		}

		public Criteria andStepcountIsNotNull() {
			addCriterion("StepCount is not null");
			return (Criteria) this;
		}

		public Criteria andStepcountEqualTo(Integer value) {
			addCriterion("StepCount =", value, "stepcount");
			return (Criteria) this;
		}

		public Criteria andStepcountNotEqualTo(Integer value) {
			addCriterion("StepCount <>", value, "stepcount");
			return (Criteria) this;
		}

		public Criteria andStepcountGreaterThan(Integer value) {
			addCriterion("StepCount >", value, "stepcount");
			return (Criteria) this;
		}

		public Criteria andStepcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("StepCount >=", value, "stepcount");
			return (Criteria) this;
		}

		public Criteria andStepcountLessThan(Integer value) {
			addCriterion("StepCount <", value, "stepcount");
			return (Criteria) this;
		}

		public Criteria andStepcountLessThanOrEqualTo(Integer value) {
			addCriterion("StepCount <=", value, "stepcount");
			return (Criteria) this;
		}

		public Criteria andStepcountIn(List<Integer> values) {
			addCriterion("StepCount in", values, "stepcount");
			return (Criteria) this;
		}

		public Criteria andStepcountNotIn(List<Integer> values) {
			addCriterion("StepCount not in", values, "stepcount");
			return (Criteria) this;
		}

		public Criteria andStepcountBetween(Integer value1, Integer value2) {
			addCriterion("StepCount between", value1, value2, "stepcount");
			return (Criteria) this;
		}

		public Criteria andStepcountNotBetween(Integer value1, Integer value2) {
			addCriterion("StepCount not between", value1, value2, "stepcount");
			return (Criteria) this;
		}

		public Criteria andRatingIsNull() {
			addCriterion("Rating is null");
			return (Criteria) this;
		}

		public Criteria andRatingIsNotNull() {
			addCriterion("Rating is not null");
			return (Criteria) this;
		}

		public Criteria andRatingEqualTo(Integer value) {
			addCriterion("Rating =", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingNotEqualTo(Integer value) {
			addCriterion("Rating <>", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingGreaterThan(Integer value) {
			addCriterion("Rating >", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingGreaterThanOrEqualTo(Integer value) {
			addCriterion("Rating >=", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingLessThan(Integer value) {
			addCriterion("Rating <", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingLessThanOrEqualTo(Integer value) {
			addCriterion("Rating <=", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingIn(List<Integer> values) {
			addCriterion("Rating in", values, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingNotIn(List<Integer> values) {
			addCriterion("Rating not in", values, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingBetween(Integer value1, Integer value2) {
			addCriterion("Rating between", value1, value2, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingNotBetween(Integer value1, Integer value2) {
			addCriterion("Rating not between", value1, value2, "rating");
			return (Criteria) this;
		}

		public Criteria andPercentageIsNull() {
			addCriterion("Percentage is null");
			return (Criteria) this;
		}

		public Criteria andPercentageIsNotNull() {
			addCriterion("Percentage is not null");
			return (Criteria) this;
		}

		public Criteria andPercentageEqualTo(Integer value) {
			addCriterion("Percentage =", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageNotEqualTo(Integer value) {
			addCriterion("Percentage <>", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageGreaterThan(Integer value) {
			addCriterion("Percentage >", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageGreaterThanOrEqualTo(Integer value) {
			addCriterion("Percentage >=", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageLessThan(Integer value) {
			addCriterion("Percentage <", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageLessThanOrEqualTo(Integer value) {
			addCriterion("Percentage <=", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageIn(List<Integer> values) {
			addCriterion("Percentage in", values, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageNotIn(List<Integer> values) {
			addCriterion("Percentage not in", values, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageBetween(Integer value1, Integer value2) {
			addCriterion("Percentage between", value1, value2, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageNotBetween(Integer value1, Integer value2) {
			addCriterion("Percentage not between", value1, value2, "percentage");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNull() {
			addCriterion("CreatedDate is null");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNotNull() {
			addCriterion("CreatedDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateddateEqualTo(Date value) {
			addCriterion("CreatedDate =", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotEqualTo(Date value) {
			addCriterion("CreatedDate <>", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThan(Date value) {
			addCriterion("CreatedDate >", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
			addCriterion("CreatedDate >=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThan(Date value) {
			addCriterion("CreatedDate <", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThanOrEqualTo(Date value) {
			addCriterion("CreatedDate <=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateIn(List<Date> values) {
			addCriterion("CreatedDate in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotIn(List<Date> values) {
			addCriterion("CreatedDate not in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateBetween(Date value1, Date value2) {
			addCriterion("CreatedDate between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotBetween(Date value1, Date value2) {
			addCriterion("CreatedDate not between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNull() {
			addCriterion("CreatedBy is null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNotNull() {
			addCriterion("CreatedBy is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyEqualTo(String value) {
			addCriterion("CreatedBy =", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotEqualTo(String value) {
			addCriterion("CreatedBy <>", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThan(String value) {
			addCriterion("CreatedBy >", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
			addCriterion("CreatedBy >=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThan(String value) {
			addCriterion("CreatedBy <", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThanOrEqualTo(String value) {
			addCriterion("CreatedBy <=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLike(String value) {
			addCriterion("CreatedBy like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotLike(String value) {
			addCriterion("CreatedBy not like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIn(List<String> values) {
			addCriterion("CreatedBy in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotIn(List<String> values) {
			addCriterion("CreatedBy not in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyBetween(String value1, String value2) {
			addCriterion("CreatedBy between", value1, value2, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotBetween(String value1, String value2) {
			addCriterion("CreatedBy not between", value1, value2, "createdby");
			return (Criteria) this;
		}

		public Criteria andRefnumberIsNull() {
			addCriterion("RefNumber is null");
			return (Criteria) this;
		}

		public Criteria andRefnumberIsNotNull() {
			addCriterion("RefNumber is not null");
			return (Criteria) this;
		}

		public Criteria andRefnumberEqualTo(String value) {
			addCriterion("RefNumber =", value, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberNotEqualTo(String value) {
			addCriterion("RefNumber <>", value, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberGreaterThan(String value) {
			addCriterion("RefNumber >", value, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberGreaterThanOrEqualTo(String value) {
			addCriterion("RefNumber >=", value, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberLessThan(String value) {
			addCriterion("RefNumber <", value, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberLessThanOrEqualTo(String value) {
			addCriterion("RefNumber <=", value, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberLike(String value) {
			addCriterion("RefNumber like", value, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberNotLike(String value) {
			addCriterion("RefNumber not like", value, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberIn(List<String> values) {
			addCriterion("RefNumber in", values, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberNotIn(List<String> values) {
			addCriterion("RefNumber not in", values, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberBetween(String value1, String value2) {
			addCriterion("RefNumber between", value1, value2, "refnumber");
			return (Criteria) this;
		}

		public Criteria andRefnumberNotBetween(String value1, String value2) {
			addCriterion("RefNumber not between", value1, value2, "refnumber");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.WFMaster
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 02 15:26:01 GST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}