package com.awf.model.orm.dbo;

public class WFProcess {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFProcess.Code
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFProcess.Name
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFProcess.Status
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFProcess.Code
	 * @return  the value of dbo.WFProcess.Code
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFProcess.Code
	 * @param code  the value for dbo.WFProcess.Code
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFProcess.Name
	 * @return  the value of dbo.WFProcess.Name
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFProcess.Name
	 * @param name  the value for dbo.WFProcess.Name
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFProcess.Status
	 * @return  the value of dbo.WFProcess.Status
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFProcess.Status
	 * @param status  the value for dbo.WFProcess.Status
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}
}