package com.awf.model.orm.dbo;

import java.util.Date;

public class WFReferences extends WFReferencesKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFReferences.Type
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFReferences.RefCode
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String refcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFReferences.RefName
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String refname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFReferences.RefHeader
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String refheader;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFReferences.RefField
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String reffield;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFReferences.AddedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String addedby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFReferences.AddedOn
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date addedon;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFReferences.Type
	 * @return  the value of dbo.WFReferences.Type
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFReferences.Type
	 * @param type  the value for dbo.WFReferences.Type
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFReferences.RefCode
	 * @return  the value of dbo.WFReferences.RefCode
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getRefcode() {
		return refcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFReferences.RefCode
	 * @param refcode  the value for dbo.WFReferences.RefCode
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setRefcode(String refcode) {
		this.refcode = refcode == null ? null : refcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFReferences.RefName
	 * @return  the value of dbo.WFReferences.RefName
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getRefname() {
		return refname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFReferences.RefName
	 * @param refname  the value for dbo.WFReferences.RefName
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setRefname(String refname) {
		this.refname = refname == null ? null : refname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFReferences.RefHeader
	 * @return  the value of dbo.WFReferences.RefHeader
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getRefheader() {
		return refheader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFReferences.RefHeader
	 * @param refheader  the value for dbo.WFReferences.RefHeader
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setRefheader(String refheader) {
		this.refheader = refheader == null ? null : refheader.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFReferences.RefField
	 * @return  the value of dbo.WFReferences.RefField
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getReffield() {
		return reffield;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFReferences.RefField
	 * @param reffield  the value for dbo.WFReferences.RefField
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setReffield(String reffield) {
		this.reffield = reffield == null ? null : reffield.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFReferences.AddedBy
	 * @return  the value of dbo.WFReferences.AddedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getAddedby() {
		return addedby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFReferences.AddedBy
	 * @param addedby  the value for dbo.WFReferences.AddedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setAddedby(String addedby) {
		this.addedby = addedby == null ? null : addedby.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFReferences.AddedOn
	 * @return  the value of dbo.WFReferences.AddedOn
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getAddedon() {
		return addedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFReferences.AddedOn
	 * @param addedon  the value for dbo.WFReferences.AddedOn
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setAddedon(Date addedon) {
		this.addedon = addedon;
	}
}