package com.awf.model.orm.dbo;

public class WFStatus {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStatus.Code
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Integer code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStatus.Name
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStatus.Code
	 * @return  the value of dbo.WFStatus.Code
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Integer getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStatus.Code
	 * @param code  the value for dbo.WFStatus.Code
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setCode(Integer code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStatus.Name
	 * @return  the value of dbo.WFStatus.Name
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStatus.Name
	 * @param name  the value for dbo.WFStatus.Name
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}