package com.awf.model.orm.dbo;

import java.util.Date;

public class WFStep extends WFStepKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.Title
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.StartDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date startdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.EndDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date enddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.Percentage
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Integer percentage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.StatusCode
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String statuscode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.Rating
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Integer rating;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.LinkedTo
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String linkedto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.CreatedDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date createddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.CreatedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String createdby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.MarkerLabel
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String markerlabel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.MarkedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String markedby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFStep.Description
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.Title
	 * @return  the value of dbo.WFStep.Title
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.Title
	 * @param title  the value for dbo.WFStep.Title
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.StartDate
	 * @return  the value of dbo.WFStep.StartDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getStartdate() {
		return startdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.StartDate
	 * @param startdate  the value for dbo.WFStep.StartDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.EndDate
	 * @return  the value of dbo.WFStep.EndDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getEnddate() {
		return enddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.EndDate
	 * @param enddate  the value for dbo.WFStep.EndDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.Percentage
	 * @return  the value of dbo.WFStep.Percentage
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Integer getPercentage() {
		return percentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.Percentage
	 * @param percentage  the value for dbo.WFStep.Percentage
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setPercentage(Integer percentage) {
		this.percentage = percentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.StatusCode
	 * @return  the value of dbo.WFStep.StatusCode
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getStatuscode() {
		return statuscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.StatusCode
	 * @param statuscode  the value for dbo.WFStep.StatusCode
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setStatuscode(String statuscode) {
		this.statuscode = statuscode == null ? null : statuscode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.Rating
	 * @return  the value of dbo.WFStep.Rating
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Integer getRating() {
		return rating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.Rating
	 * @param rating  the value for dbo.WFStep.Rating
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setRating(Integer rating) {
		this.rating = rating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.LinkedTo
	 * @return  the value of dbo.WFStep.LinkedTo
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getLinkedto() {
		return linkedto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.LinkedTo
	 * @param linkedto  the value for dbo.WFStep.LinkedTo
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setLinkedto(String linkedto) {
		this.linkedto = linkedto == null ? null : linkedto.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.CreatedDate
	 * @return  the value of dbo.WFStep.CreatedDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getCreateddate() {
		return createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.CreatedDate
	 * @param createddate  the value for dbo.WFStep.CreatedDate
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.CreatedBy
	 * @return  the value of dbo.WFStep.CreatedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getCreatedby() {
		return createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.CreatedBy
	 * @param createdby  the value for dbo.WFStep.CreatedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setCreatedby(String createdby) {
		this.createdby = createdby == null ? null : createdby.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.MarkerLabel
	 * @return  the value of dbo.WFStep.MarkerLabel
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getMarkerlabel() {
		return markerlabel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.MarkerLabel
	 * @param markerlabel  the value for dbo.WFStep.MarkerLabel
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setMarkerlabel(String markerlabel) {
		this.markerlabel = markerlabel == null ? null : markerlabel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.MarkedBy
	 * @return  the value of dbo.WFStep.MarkedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getMarkedby() {
		return markedby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.MarkedBy
	 * @param markedby  the value for dbo.WFStep.MarkedBy
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setMarkedby(String markedby) {
		this.markedby = markedby == null ? null : markedby.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFStep.Description
	 * @return  the value of dbo.WFStep.Description
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFStep.Description
	 * @param description  the value for dbo.WFStep.Description
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}