package com.awf.model.orm.dbo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WFStepExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public WFStepExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andStepcodeIsNull() {
			addCriterion("StepCode is null");
			return (Criteria) this;
		}

		public Criteria andStepcodeIsNotNull() {
			addCriterion("StepCode is not null");
			return (Criteria) this;
		}

		public Criteria andStepcodeEqualTo(String value) {
			addCriterion("StepCode =", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeNotEqualTo(String value) {
			addCriterion("StepCode <>", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeGreaterThan(String value) {
			addCriterion("StepCode >", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeGreaterThanOrEqualTo(String value) {
			addCriterion("StepCode >=", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeLessThan(String value) {
			addCriterion("StepCode <", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeLessThanOrEqualTo(String value) {
			addCriterion("StepCode <=", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeLike(String value) {
			addCriterion("StepCode like", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeNotLike(String value) {
			addCriterion("StepCode not like", value, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeIn(List<String> values) {
			addCriterion("StepCode in", values, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeNotIn(List<String> values) {
			addCriterion("StepCode not in", values, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeBetween(String value1, String value2) {
			addCriterion("StepCode between", value1, value2, "stepcode");
			return (Criteria) this;
		}

		public Criteria andStepcodeNotBetween(String value1, String value2) {
			addCriterion("StepCode not between", value1, value2, "stepcode");
			return (Criteria) this;
		}

		public Criteria andSerialnoIsNull() {
			addCriterion("SerialNo is null");
			return (Criteria) this;
		}

		public Criteria andSerialnoIsNotNull() {
			addCriterion("SerialNo is not null");
			return (Criteria) this;
		}

		public Criteria andSerialnoEqualTo(Integer value) {
			addCriterion("SerialNo =", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotEqualTo(Integer value) {
			addCriterion("SerialNo <>", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoGreaterThan(Integer value) {
			addCriterion("SerialNo >", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoGreaterThanOrEqualTo(Integer value) {
			addCriterion("SerialNo >=", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoLessThan(Integer value) {
			addCriterion("SerialNo <", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoLessThanOrEqualTo(Integer value) {
			addCriterion("SerialNo <=", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoIn(List<Integer> values) {
			addCriterion("SerialNo in", values, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotIn(List<Integer> values) {
			addCriterion("SerialNo not in", values, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoBetween(Integer value1, Integer value2) {
			addCriterion("SerialNo between", value1, value2, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotBetween(Integer value1, Integer value2) {
			addCriterion("SerialNo not between", value1, value2, "serialno");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("Title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("Title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("Title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("Title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("Title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("Title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("Title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("Title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("Title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("Title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("Title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("Title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("Title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("Title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andStartdateIsNull() {
			addCriterion("StartDate is null");
			return (Criteria) this;
		}

		public Criteria andStartdateIsNotNull() {
			addCriterion("StartDate is not null");
			return (Criteria) this;
		}

		public Criteria andStartdateEqualTo(Date value) {
			addCriterion("StartDate =", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateNotEqualTo(Date value) {
			addCriterion("StartDate <>", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateGreaterThan(Date value) {
			addCriterion("StartDate >", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
			addCriterion("StartDate >=", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateLessThan(Date value) {
			addCriterion("StartDate <", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateLessThanOrEqualTo(Date value) {
			addCriterion("StartDate <=", value, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateIn(List<Date> values) {
			addCriterion("StartDate in", values, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateNotIn(List<Date> values) {
			addCriterion("StartDate not in", values, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateBetween(Date value1, Date value2) {
			addCriterion("StartDate between", value1, value2, "startdate");
			return (Criteria) this;
		}

		public Criteria andStartdateNotBetween(Date value1, Date value2) {
			addCriterion("StartDate not between", value1, value2, "startdate");
			return (Criteria) this;
		}

		public Criteria andEnddateIsNull() {
			addCriterion("EndDate is null");
			return (Criteria) this;
		}

		public Criteria andEnddateIsNotNull() {
			addCriterion("EndDate is not null");
			return (Criteria) this;
		}

		public Criteria andEnddateEqualTo(Date value) {
			addCriterion("EndDate =", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateNotEqualTo(Date value) {
			addCriterion("EndDate <>", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateGreaterThan(Date value) {
			addCriterion("EndDate >", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
			addCriterion("EndDate >=", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateLessThan(Date value) {
			addCriterion("EndDate <", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateLessThanOrEqualTo(Date value) {
			addCriterion("EndDate <=", value, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateIn(List<Date> values) {
			addCriterion("EndDate in", values, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateNotIn(List<Date> values) {
			addCriterion("EndDate not in", values, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateBetween(Date value1, Date value2) {
			addCriterion("EndDate between", value1, value2, "enddate");
			return (Criteria) this;
		}

		public Criteria andEnddateNotBetween(Date value1, Date value2) {
			addCriterion("EndDate not between", value1, value2, "enddate");
			return (Criteria) this;
		}

		public Criteria andPercentageIsNull() {
			addCriterion("Percentage is null");
			return (Criteria) this;
		}

		public Criteria andPercentageIsNotNull() {
			addCriterion("Percentage is not null");
			return (Criteria) this;
		}

		public Criteria andPercentageEqualTo(Integer value) {
			addCriterion("Percentage =", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageNotEqualTo(Integer value) {
			addCriterion("Percentage <>", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageGreaterThan(Integer value) {
			addCriterion("Percentage >", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageGreaterThanOrEqualTo(Integer value) {
			addCriterion("Percentage >=", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageLessThan(Integer value) {
			addCriterion("Percentage <", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageLessThanOrEqualTo(Integer value) {
			addCriterion("Percentage <=", value, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageIn(List<Integer> values) {
			addCriterion("Percentage in", values, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageNotIn(List<Integer> values) {
			addCriterion("Percentage not in", values, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageBetween(Integer value1, Integer value2) {
			addCriterion("Percentage between", value1, value2, "percentage");
			return (Criteria) this;
		}

		public Criteria andPercentageNotBetween(Integer value1, Integer value2) {
			addCriterion("Percentage not between", value1, value2, "percentage");
			return (Criteria) this;
		}

		public Criteria andStatuscodeIsNull() {
			addCriterion("StatusCode is null");
			return (Criteria) this;
		}

		public Criteria andStatuscodeIsNotNull() {
			addCriterion("StatusCode is not null");
			return (Criteria) this;
		}

		public Criteria andStatuscodeEqualTo(String value) {
			addCriterion("StatusCode =", value, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeNotEqualTo(String value) {
			addCriterion("StatusCode <>", value, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeGreaterThan(String value) {
			addCriterion("StatusCode >", value, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeGreaterThanOrEqualTo(String value) {
			addCriterion("StatusCode >=", value, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeLessThan(String value) {
			addCriterion("StatusCode <", value, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeLessThanOrEqualTo(String value) {
			addCriterion("StatusCode <=", value, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeLike(String value) {
			addCriterion("StatusCode like", value, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeNotLike(String value) {
			addCriterion("StatusCode not like", value, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeIn(List<String> values) {
			addCriterion("StatusCode in", values, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeNotIn(List<String> values) {
			addCriterion("StatusCode not in", values, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeBetween(String value1, String value2) {
			addCriterion("StatusCode between", value1, value2, "statuscode");
			return (Criteria) this;
		}

		public Criteria andStatuscodeNotBetween(String value1, String value2) {
			addCriterion("StatusCode not between", value1, value2, "statuscode");
			return (Criteria) this;
		}

		public Criteria andRatingIsNull() {
			addCriterion("Rating is null");
			return (Criteria) this;
		}

		public Criteria andRatingIsNotNull() {
			addCriterion("Rating is not null");
			return (Criteria) this;
		}

		public Criteria andRatingEqualTo(Integer value) {
			addCriterion("Rating =", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingNotEqualTo(Integer value) {
			addCriterion("Rating <>", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingGreaterThan(Integer value) {
			addCriterion("Rating >", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingGreaterThanOrEqualTo(Integer value) {
			addCriterion("Rating >=", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingLessThan(Integer value) {
			addCriterion("Rating <", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingLessThanOrEqualTo(Integer value) {
			addCriterion("Rating <=", value, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingIn(List<Integer> values) {
			addCriterion("Rating in", values, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingNotIn(List<Integer> values) {
			addCriterion("Rating not in", values, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingBetween(Integer value1, Integer value2) {
			addCriterion("Rating between", value1, value2, "rating");
			return (Criteria) this;
		}

		public Criteria andRatingNotBetween(Integer value1, Integer value2) {
			addCriterion("Rating not between", value1, value2, "rating");
			return (Criteria) this;
		}

		public Criteria andLinkedtoIsNull() {
			addCriterion("LinkedTo is null");
			return (Criteria) this;
		}

		public Criteria andLinkedtoIsNotNull() {
			addCriterion("LinkedTo is not null");
			return (Criteria) this;
		}

		public Criteria andLinkedtoEqualTo(String value) {
			addCriterion("LinkedTo =", value, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoNotEqualTo(String value) {
			addCriterion("LinkedTo <>", value, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoGreaterThan(String value) {
			addCriterion("LinkedTo >", value, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoGreaterThanOrEqualTo(String value) {
			addCriterion("LinkedTo >=", value, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoLessThan(String value) {
			addCriterion("LinkedTo <", value, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoLessThanOrEqualTo(String value) {
			addCriterion("LinkedTo <=", value, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoLike(String value) {
			addCriterion("LinkedTo like", value, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoNotLike(String value) {
			addCriterion("LinkedTo not like", value, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoIn(List<String> values) {
			addCriterion("LinkedTo in", values, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoNotIn(List<String> values) {
			addCriterion("LinkedTo not in", values, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoBetween(String value1, String value2) {
			addCriterion("LinkedTo between", value1, value2, "linkedto");
			return (Criteria) this;
		}

		public Criteria andLinkedtoNotBetween(String value1, String value2) {
			addCriterion("LinkedTo not between", value1, value2, "linkedto");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNull() {
			addCriterion("CreatedDate is null");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNotNull() {
			addCriterion("CreatedDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateddateEqualTo(Date value) {
			addCriterion("CreatedDate =", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotEqualTo(Date value) {
			addCriterion("CreatedDate <>", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThan(Date value) {
			addCriterion("CreatedDate >", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
			addCriterion("CreatedDate >=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThan(Date value) {
			addCriterion("CreatedDate <", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThanOrEqualTo(Date value) {
			addCriterion("CreatedDate <=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateIn(List<Date> values) {
			addCriterion("CreatedDate in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotIn(List<Date> values) {
			addCriterion("CreatedDate not in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateBetween(Date value1, Date value2) {
			addCriterion("CreatedDate between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotBetween(Date value1, Date value2) {
			addCriterion("CreatedDate not between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNull() {
			addCriterion("CreatedBy is null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNotNull() {
			addCriterion("CreatedBy is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyEqualTo(String value) {
			addCriterion("CreatedBy =", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotEqualTo(String value) {
			addCriterion("CreatedBy <>", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThan(String value) {
			addCriterion("CreatedBy >", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
			addCriterion("CreatedBy >=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThan(String value) {
			addCriterion("CreatedBy <", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThanOrEqualTo(String value) {
			addCriterion("CreatedBy <=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLike(String value) {
			addCriterion("CreatedBy like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotLike(String value) {
			addCriterion("CreatedBy not like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIn(List<String> values) {
			addCriterion("CreatedBy in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotIn(List<String> values) {
			addCriterion("CreatedBy not in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyBetween(String value1, String value2) {
			addCriterion("CreatedBy between", value1, value2, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotBetween(String value1, String value2) {
			addCriterion("CreatedBy not between", value1, value2, "createdby");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelIsNull() {
			addCriterion("MarkerLabel is null");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelIsNotNull() {
			addCriterion("MarkerLabel is not null");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelEqualTo(String value) {
			addCriterion("MarkerLabel =", value, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelNotEqualTo(String value) {
			addCriterion("MarkerLabel <>", value, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelGreaterThan(String value) {
			addCriterion("MarkerLabel >", value, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelGreaterThanOrEqualTo(String value) {
			addCriterion("MarkerLabel >=", value, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelLessThan(String value) {
			addCriterion("MarkerLabel <", value, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelLessThanOrEqualTo(String value) {
			addCriterion("MarkerLabel <=", value, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelLike(String value) {
			addCriterion("MarkerLabel like", value, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelNotLike(String value) {
			addCriterion("MarkerLabel not like", value, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelIn(List<String> values) {
			addCriterion("MarkerLabel in", values, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelNotIn(List<String> values) {
			addCriterion("MarkerLabel not in", values, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelBetween(String value1, String value2) {
			addCriterion("MarkerLabel between", value1, value2, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkerlabelNotBetween(String value1, String value2) {
			addCriterion("MarkerLabel not between", value1, value2, "markerlabel");
			return (Criteria) this;
		}

		public Criteria andMarkedbyIsNull() {
			addCriterion("MarkedBy is null");
			return (Criteria) this;
		}

		public Criteria andMarkedbyIsNotNull() {
			addCriterion("MarkedBy is not null");
			return (Criteria) this;
		}

		public Criteria andMarkedbyEqualTo(String value) {
			addCriterion("MarkedBy =", value, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyNotEqualTo(String value) {
			addCriterion("MarkedBy <>", value, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyGreaterThan(String value) {
			addCriterion("MarkedBy >", value, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyGreaterThanOrEqualTo(String value) {
			addCriterion("MarkedBy >=", value, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyLessThan(String value) {
			addCriterion("MarkedBy <", value, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyLessThanOrEqualTo(String value) {
			addCriterion("MarkedBy <=", value, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyLike(String value) {
			addCriterion("MarkedBy like", value, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyNotLike(String value) {
			addCriterion("MarkedBy not like", value, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyIn(List<String> values) {
			addCriterion("MarkedBy in", values, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyNotIn(List<String> values) {
			addCriterion("MarkedBy not in", values, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyBetween(String value1, String value2) {
			addCriterion("MarkedBy between", value1, value2, "markedby");
			return (Criteria) this;
		}

		public Criteria andMarkedbyNotBetween(String value1, String value2) {
			addCriterion("MarkedBy not between", value1, value2, "markedby");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.WFStep
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 02 15:26:01 GST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}