package com.awf.model.orm.dbo;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class WFUsersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public WFUsersExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUsercodeIsNull() {
			addCriterion("Usercode is null");
			return (Criteria) this;
		}

		public Criteria andUsercodeIsNotNull() {
			addCriterion("Usercode is not null");
			return (Criteria) this;
		}

		public Criteria andUsercodeEqualTo(Integer value) {
			addCriterion("Usercode =", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeNotEqualTo(Integer value) {
			addCriterion("Usercode <>", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeGreaterThan(Integer value) {
			addCriterion("Usercode >", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("Usercode >=", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeLessThan(Integer value) {
			addCriterion("Usercode <", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeLessThanOrEqualTo(Integer value) {
			addCriterion("Usercode <=", value, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeIn(List<Integer> values) {
			addCriterion("Usercode in", values, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeNotIn(List<Integer> values) {
			addCriterion("Usercode not in", values, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeBetween(Integer value1, Integer value2) {
			addCriterion("Usercode between", value1, value2, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsercodeNotBetween(Integer value1, Integer value2) {
			addCriterion("Usercode not between", value1, value2, "usercode");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("Username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("Username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("Username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("Username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("Username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("Username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("Username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("Username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("Username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("Username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("Username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("Username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("Username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("Username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("Password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("Password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("Password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("Password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("Password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("Password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("Password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("Password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("Password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("Password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("Password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("Password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("Password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("Password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("Name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("Name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("Name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("Name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("Name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("Name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("Name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("Name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("Name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("Name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("Name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("Name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("Name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("Name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andAccessIsNull() {
			addCriterion("Access is null");
			return (Criteria) this;
		}

		public Criteria andAccessIsNotNull() {
			addCriterion("Access is not null");
			return (Criteria) this;
		}

		public Criteria andAccessEqualTo(String value) {
			addCriterion("Access =", value, "access");
			return (Criteria) this;
		}

		public Criteria andAccessNotEqualTo(String value) {
			addCriterion("Access <>", value, "access");
			return (Criteria) this;
		}

		public Criteria andAccessGreaterThan(String value) {
			addCriterion("Access >", value, "access");
			return (Criteria) this;
		}

		public Criteria andAccessGreaterThanOrEqualTo(String value) {
			addCriterion("Access >=", value, "access");
			return (Criteria) this;
		}

		public Criteria andAccessLessThan(String value) {
			addCriterion("Access <", value, "access");
			return (Criteria) this;
		}

		public Criteria andAccessLessThanOrEqualTo(String value) {
			addCriterion("Access <=", value, "access");
			return (Criteria) this;
		}

		public Criteria andAccessLike(String value) {
			addCriterion("Access like", value, "access");
			return (Criteria) this;
		}

		public Criteria andAccessNotLike(String value) {
			addCriterion("Access not like", value, "access");
			return (Criteria) this;
		}

		public Criteria andAccessIn(List<String> values) {
			addCriterion("Access in", values, "access");
			return (Criteria) this;
		}

		public Criteria andAccessNotIn(List<String> values) {
			addCriterion("Access not in", values, "access");
			return (Criteria) this;
		}

		public Criteria andAccessBetween(String value1, String value2) {
			addCriterion("Access between", value1, value2, "access");
			return (Criteria) this;
		}

		public Criteria andAccessNotBetween(String value1, String value2) {
			addCriterion("Access not between", value1, value2, "access");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcIsNull() {
			addCriterion("LastLoginSrc is null");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcIsNotNull() {
			addCriterion("LastLoginSrc is not null");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcEqualTo(String value) {
			addCriterion("LastLoginSrc =", value, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcNotEqualTo(String value) {
			addCriterion("LastLoginSrc <>", value, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcGreaterThan(String value) {
			addCriterion("LastLoginSrc >", value, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcGreaterThanOrEqualTo(String value) {
			addCriterion("LastLoginSrc >=", value, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcLessThan(String value) {
			addCriterion("LastLoginSrc <", value, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcLessThanOrEqualTo(String value) {
			addCriterion("LastLoginSrc <=", value, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcLike(String value) {
			addCriterion("LastLoginSrc like", value, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcNotLike(String value) {
			addCriterion("LastLoginSrc not like", value, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcIn(List<String> values) {
			addCriterion("LastLoginSrc in", values, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcNotIn(List<String> values) {
			addCriterion("LastLoginSrc not in", values, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcBetween(String value1, String value2) {
			addCriterion("LastLoginSrc between", value1, value2, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginsrcNotBetween(String value1, String value2) {
			addCriterion("LastLoginSrc not between", value1, value2, "lastloginsrc");
			return (Criteria) this;
		}

		public Criteria andLastloginIsNull() {
			addCriterion("LastLogin is null");
			return (Criteria) this;
		}

		public Criteria andLastloginIsNotNull() {
			addCriterion("LastLogin is not null");
			return (Criteria) this;
		}

		public Criteria andLastloginEqualTo(Date value) {
			addCriterion("LastLogin =", value, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andLastloginNotEqualTo(Date value) {
			addCriterion("LastLogin <>", value, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andLastloginGreaterThan(Date value) {
			addCriterion("LastLogin >", value, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andLastloginGreaterThanOrEqualTo(Date value) {
			addCriterion("LastLogin >=", value, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andLastloginLessThan(Date value) {
			addCriterion("LastLogin <", value, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andLastloginLessThanOrEqualTo(Date value) {
			addCriterion("LastLogin <=", value, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andLastloginIn(List<Date> values) {
			addCriterion("LastLogin in", values, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andLastloginNotIn(List<Date> values) {
			addCriterion("LastLogin not in", values, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andLastloginBetween(Date value1, Date value2) {
			addCriterion("LastLogin between", value1, value2, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andLastloginNotBetween(Date value1, Date value2) {
			addCriterion("LastLogin not between", value1, value2, "lastlogin");
			return (Criteria) this;
		}

		public Criteria andActiveIsNull() {
			addCriterion("Active is null");
			return (Criteria) this;
		}

		public Criteria andActiveIsNotNull() {
			addCriterion("Active is not null");
			return (Criteria) this;
		}

		public Criteria andActiveEqualTo(String value) {
			addCriterion("Active =", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotEqualTo(String value) {
			addCriterion("Active <>", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThan(String value) {
			addCriterion("Active >", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThanOrEqualTo(String value) {
			addCriterion("Active >=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThan(String value) {
			addCriterion("Active <", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThanOrEqualTo(String value) {
			addCriterion("Active <=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLike(String value) {
			addCriterion("Active like", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotLike(String value) {
			addCriterion("Active not like", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveIn(List<String> values) {
			addCriterion("Active in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotIn(List<String> values) {
			addCriterion("Active not in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveBetween(String value1, String value2) {
			addCriterion("Active between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotBetween(String value1, String value2) {
			addCriterion("Active not between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andSysnameIsNull() {
			addCriterion("Sysname is null");
			return (Criteria) this;
		}

		public Criteria andSysnameIsNotNull() {
			addCriterion("Sysname is not null");
			return (Criteria) this;
		}

		public Criteria andSysnameEqualTo(String value) {
			addCriterion("Sysname =", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameNotEqualTo(String value) {
			addCriterion("Sysname <>", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameGreaterThan(String value) {
			addCriterion("Sysname >", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameGreaterThanOrEqualTo(String value) {
			addCriterion("Sysname >=", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameLessThan(String value) {
			addCriterion("Sysname <", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameLessThanOrEqualTo(String value) {
			addCriterion("Sysname <=", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameLike(String value) {
			addCriterion("Sysname like", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameNotLike(String value) {
			addCriterion("Sysname not like", value, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameIn(List<String> values) {
			addCriterion("Sysname in", values, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameNotIn(List<String> values) {
			addCriterion("Sysname not in", values, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameBetween(String value1, String value2) {
			addCriterion("Sysname between", value1, value2, "sysname");
			return (Criteria) this;
		}

		public Criteria andSysnameNotBetween(String value1, String value2) {
			addCriterion("Sysname not between", value1, value2, "sysname");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFUsers
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.WFUsers
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 05 12:32:55 GST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}