package com.awf.model.orm.dbo;

import java.util.Date;

public class WFUsers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFUsers.Usercode
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Integer usercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFUsers.Username
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFUsers.Password
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFUsers.Name
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFUsers.Access
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String access;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFUsers.LastLoginSrc
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String lastloginsrc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFUsers.LastLogin
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private Date lastlogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFUsers.Active
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String active;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFUsers.Sysname
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	private String sysname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFUsers.Usercode
	 * @return  the value of dbo.WFUsers.Usercode
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Integer getUsercode() {
		return usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFUsers.Usercode
	 * @param usercode  the value for dbo.WFUsers.Usercode
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setUsercode(Integer usercode) {
		this.usercode = usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFUsers.Username
	 * @return  the value of dbo.WFUsers.Username
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFUsers.Username
	 * @param username  the value for dbo.WFUsers.Username
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFUsers.Password
	 * @return  the value of dbo.WFUsers.Password
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFUsers.Password
	 * @param password  the value for dbo.WFUsers.Password
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFUsers.Name
	 * @return  the value of dbo.WFUsers.Name
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFUsers.Name
	 * @param name  the value for dbo.WFUsers.Name
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFUsers.Access
	 * @return  the value of dbo.WFUsers.Access
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getAccess() {
		return access;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFUsers.Access
	 * @param access  the value for dbo.WFUsers.Access
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setAccess(String access) {
		this.access = access == null ? null : access.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFUsers.LastLoginSrc
	 * @return  the value of dbo.WFUsers.LastLoginSrc
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getLastloginsrc() {
		return lastloginsrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFUsers.LastLoginSrc
	 * @param lastloginsrc  the value for dbo.WFUsers.LastLoginSrc
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setLastloginsrc(String lastloginsrc) {
		this.lastloginsrc = lastloginsrc == null ? null : lastloginsrc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFUsers.LastLogin
	 * @return  the value of dbo.WFUsers.LastLogin
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public Date getLastlogin() {
		return lastlogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFUsers.LastLogin
	 * @param lastlogin  the value for dbo.WFUsers.LastLogin
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setLastlogin(Date lastlogin) {
		this.lastlogin = lastlogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFUsers.Active
	 * @return  the value of dbo.WFUsers.Active
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFUsers.Active
	 * @param active  the value for dbo.WFUsers.Active
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setActive(String active) {
		this.active = active == null ? null : active.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFUsers.Sysname
	 * @return  the value of dbo.WFUsers.Sysname
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public String getSysname() {
		return sysname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFUsers.Sysname
	 * @param sysname  the value for dbo.WFUsers.Sysname
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	public void setSysname(String sysname) {
		this.sysname = sysname == null ? null : sysname.trim();
	}
}