package com.awf.model.mapper;

import com.awf.model.dbo.IMConnectionsDBO;
import com.awf.model.orm.dbo.IMConnections;
import com.awf.model.orm.dbo.IMConnectionsExample;
import com.awf.model.orm.dbo.IMConnectionsKey;
import com.awf.model.orm.dbo.IMConnectionsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IMConnectionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    long countByExample(IMConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int deleteByExample(IMConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int deleteByPrimaryKey(IMConnectionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int insert(IMConnectionsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int insertSelective(IMConnectionsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    List<IMConnectionsWithBLOBs> selectByExampleWithBLOBs(IMConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    List<IMConnections> selectByExample(IMConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    IMConnectionsWithBLOBs selectByPrimaryKey(IMConnectionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int updateByExampleSelective(@Param("record") IMConnectionsWithBLOBs record, @Param("example") IMConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") IMConnectionsWithBLOBs record, @Param("example") IMConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int updateByExample(@Param("record") IMConnections record, @Param("example") IMConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int updateByPrimaryKeySelective(IMConnectionsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int updateByPrimaryKeyWithBLOBs(IMConnectionsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.IMConnections
     *
     * @mbg.generated Wed Dec 12 10:36:58 GST 2018
     */
    int updateByPrimaryKey(IMConnections record);
    
     
    IMConnectionsDBO checkConnection(@Param("currentUser") Integer currentUser, @Param("intendedUser") Integer intendedUser);

	List<IMConnectionsDBO> findActiveConnections(@Param("usercode") Integer usercode);

	void deleteConnection(IMConnectionsDBO connection); 
    
}