package com.awf.model.mapper;

import com.awf.model.dbo.WFContentDBO;
import com.awf.model.dbo.WFReferencesDBO;
import com.awf.model.orm.dbo.WFContent;
import com.awf.model.orm.dbo.WFContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.awf.model.orm.dbo.WFContentKey;

public interface WFContentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	long countByExample(WFContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByExample(WFContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByPrimaryKey(WFContentKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insert(WFContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insertSelective(WFContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	List<WFContent> selectByExample(WFContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	WFContent selectByPrimaryKey(WFContentKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExampleSelective(@Param("record") WFContent record, @Param("example") WFContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExample(@Param("record") WFContent record, @Param("example") WFContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKeySelective(WFContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFContent
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKey(WFContent record);

	List<WFContentDBO> fetchContents(@Param("stepcode") String stepcode, @Param("serialno") Integer serialno);  
}