package com.awf.model.mapper;

import com.awf.model.dbo.WFMasterDBO;
import com.awf.model.orm.dbo.WFMaster;
import com.awf.model.orm.dbo.WFMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WFMasterMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	long countByExample(WFMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByExample(WFMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByPrimaryKey(String stepsequence);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insert(WFMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insertSelective(WFMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	List<WFMaster> selectByExampleWithBLOBs(WFMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	List<WFMaster> selectByExample(WFMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	WFMaster selectByPrimaryKey(String stepsequence);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExampleSelective(@Param("record") WFMaster record, @Param("example") WFMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") WFMaster record, @Param("example") WFMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExample(@Param("record") WFMaster record, @Param("example") WFMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKeySelective(WFMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(WFMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFMaster
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKey(WFMaster record);

	List<WFMasterDBO> fetchWorkflows();

	Integer getMaxDocNumber();
}