package com.awf.model.mapper;

import com.awf.model.orm.dbo.WFProcess;
import com.awf.model.orm.dbo.WFProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WFProcessMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	long countByExample(WFProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByExample(WFProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insert(WFProcess record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insertSelective(WFProcess record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	List<WFProcess> selectByExample(WFProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	WFProcess selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExampleSelective(@Param("record") WFProcess record, @Param("example") WFProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExample(@Param("record") WFProcess record, @Param("example") WFProcessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKeySelective(WFProcess record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFProcess
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKey(WFProcess record);
}