package com.awf.model.mapper;

import com.awf.model.dbo.WFMasterDBO;
import com.awf.model.dbo.WFReferencesDBO;
import com.awf.model.dbo.WFStepDBO;
import com.awf.model.orm.dbo.WFReferences;
import com.awf.model.orm.dbo.WFReferencesExample;
import com.awf.model.orm.dbo.WFReferencesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WFReferencesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	long countByExample(WFReferencesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByExample(WFReferencesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByPrimaryKey(WFReferencesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insert(WFReferences record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insertSelective(WFReferences record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	List<WFReferences> selectByExample(WFReferencesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	WFReferences selectByPrimaryKey(WFReferencesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExampleSelective(@Param("record") WFReferences record, @Param("example") WFReferencesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExample(@Param("record") WFReferences record, @Param("example") WFReferencesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKeySelective(WFReferences record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFReferences
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKey(WFReferences record);

	List<WFReferencesDBO> fetchReferences(@Param("stepcode") String stepcode, @Param("serialno") Integer serialno);

	List<WFReferencesDBO> findDistReferences(@Param("stepcode")  String stepcode);   
}