package com.awf.model.mapper;

import com.awf.model.dbo.WFMasterDBO;
import com.awf.model.dbo.WFStepDBO;
import com.awf.model.orm.dbo.WFStep;
import com.awf.model.orm.dbo.WFStepExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.awf.model.orm.dbo.WFStepKey;

public interface WFStepMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	long countByExample(WFStepExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByExample(WFStepExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int deleteByPrimaryKey(WFStepKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insert(WFStep record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int insertSelective(WFStep record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	List<WFStep> selectByExampleWithBLOBs(WFStepExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	List<WFStep> selectByExample(WFStepExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	WFStep selectByPrimaryKey(WFStepKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExampleSelective(@Param("record") WFStep record, @Param("example") WFStepExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") WFStep record, @Param("example") WFStepExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByExample(@Param("record") WFStep record, @Param("example") WFStepExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKeySelective(WFStep record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(WFStep record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFStep
	 * @mbg.generated  Fri Apr 12 12:46:47 IST 2019
	 */
	int updateByPrimaryKey(WFStep record);

	List<WFStepDBO> fetchWorkflowSteps(WFMasterDBO workflow);

	void insertContent(WFStepDBO stepSelected);
	
	
	
	
	
}